'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Eye, FileText, Send } from 'lucide-react';
import { vx, VX_BUCKET } from '../../../vxClient';

const KEY='verifyx-student';
const fmt=v=>Number.isFinite(Number(v))?Number(v).toFixed(3):'—';

export default function StudentAssignment(){
  const {id}=useParams(); const assignmentId=Number(id);
  const [identity,setIdentity]=useState(null); const [assignment,setAssignment]=useState(null); const [questions,setQuestions]=useState([]); const [subs,setSubs]=useState([]); const [error,setError]=useState('');
  useEffect(()=>{try{setIdentity(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{}},[]);
  useEffect(()=>{if(identity&&assignmentId)load()},[identity,assignmentId]);
  async function load(){setError('');const [{data:a,error:ae},{data:q,error:qe},{data:s,error:se}]=await Promise.all([vx.from('vx_assignments').select('*').eq('id',assignmentId).single(),vx.rpc('vx_get_student_questions',{p_assignment_id:assignmentId}),vx.rpc('vx_get_student_submissions',{p_student_code:identity.studentCode,p_assignment_id:assignmentId})]);if(ae||qe||se)setError((ae||qe||se).message);setAssignment(a||null);setQuestions(q||[]);setSubs(s||[])}
  async function openFile(path){const {data,error}=await vx.storage.from(VX_BUCKET).createSignedUrl(path,300);if(error)return setError(error.message);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
  async function submit(e,q){e.preventDefault();const fd=new FormData(e.currentTarget);const {data,error}=await vx.rpc('vx_submit_mass_properties',{p_student_code:identity.studentCode,p_full_name:identity.fullName,p_question_id:q.id,p_volume:Number(fd.get('volume')).toFixed(3),p_surface_area:Number(fd.get('area')).toFixed(3),p_mass:Number(fd.get('mass')).toFixed(3),p_com_x:Number(fd.get('x')).toFixed(3),p_com_y:Number(fd.get('y')).toFixed(3),p_com_z:Number(fd.get('z')).toFixed(3)});if(error)return setError(error.message);e.currentTarget.reset();alert(`คะแนน ${Number(data.score).toFixed(0)}/100`);await load()}
  if(!identity)return <main className="vx-page"><div className="vx-wrap"><div className="vx-empty">กรุณาเข้าสู่ Student Mode ก่อน</div></div></main>;
  if(!assignment)return <main className="vx-page"><div className="vx-wrap"><div className="vx-empty">กำลังโหลด Assignment...</div></div></main>;
  return <main className="vx-page"><div className="vx-wrap"><header className="vx-top"><div><Link className="vx-file" href="/verifyx/student"><ArrowLeft size={15}/>Assignments</Link><p className="vx-kicker" style={{marginTop:14}}>ASSIGNMENT</p><h1>{assignment.title}</h1><p>{assignment.course||'ไม่ระบุวิชา'} · {assignment.max_attempts} attempts / ข้อ</p></div></header>{error&&<div className="vx-error">{error}</div>}<section className="vx-list">{questions.map(q=>{const qSubs=subs.filter(s=>s.question_id===q.id);const remaining=Math.max(0,assignment.max_attempts-qSubs.length);const latest=qSubs[0];return <article className="vx-card" key={q.id}><div className="vx-top" style={{marginBottom:10}}><div><p className="vx-kicker">QUESTION {q.question_number}</p><h3>{q.title}</h3></div><span className="vx-status">เหลือ {remaining}/{assignment.max_attempts}</span></div><div className="vx-toolbar"><button className="vx-file" onClick={()=>openFile(q.drawing_path)}><FileText size={15}/>Drawing PDF</button>{q.show_model_preview&&q.model_image_path&&<button className="vx-file" onClick={()=>openFile(q.model_image_path)}><Eye size={15}/>Model Reference</button>}</div><form className="vx-form" onSubmit={e=>submit(e,q)}><div className="vx-mass-grid"><label>Volume mm³<input name="volume" type="number" step="0.001" required disabled={!remaining}/></label><label>Surface Area mm²<input name="area" type="number" step="0.001" required disabled={!remaining}/></label><label>Mass g<input name="mass" type="number" step="0.001" required disabled={!remaining}/></label></div><div className="vx-mass-grid"><label>COM X<input name="x" type="number" step="0.001" required disabled={!remaining}/></label><label>COM Y<input name="y" type="number" step="0.001" required disabled={!remaining}/></label><label>COM Z<input name="z" type="number" step="0.001" required disabled={!remaining}/></label></div><button className="vx-btn primary" disabled={!remaining}><Send size={15}/>{remaining?'ส่งและตรวจคะแนน':'ส่งครบแล้ว'}</button></form>{latest&&<div className="vx-result"><div className="vx-score">{Number(latest.score).toFixed(0)}/100</div><div className="vx-tags"><span>V {fmt(latest.volume)}</span><span>A {fmt(latest.surface_area)}</span><span>M {fmt(latest.mass)}</span><span>COM {fmt(latest.com_x)}, {fmt(latest.com_y)}, {fmt(latest.com_z)}</span></div></div>}</article>})}</section></div></main>;
}
