'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Eye, FileText, Image as ImageIcon, Plus } from 'lucide-react';
import { vx, VX_BUCKET } from '../../../vxClient';

const emptyDraft={title:'',volume:'',area:'',mass:'',x:'',y:'',z:'',preview:false};

export default function AssignmentDetail(){
 const {id}=useParams(); const assignmentId=Number(id); const [assignment,setAssignment]=useState(null); const [questions,setQuestions]=useState([]); const [error,setError]=useState(''); const [show,setShow]=useState(false); const [saving,setSaving]=useState(false); const [draft,setDraft]=useState(emptyDraft); const [draftRestored,setDraftRestored]=useState(false);
 const nextNo=useMemo(()=>questions.length?Math.max(...questions.map(q=>q.question_number))+1:1,[questions]);
 const draftKey=useMemo(()=>`verifyx-question-draft-${assignmentId}-${nextNo}`,[assignmentId,nextNo]);
 async function load(){setError('');const [{data:a,error:ae},{data:q,error:qe}]=await Promise.all([vx.from('vx_assignments').select('*').eq('id',assignmentId).single(),vx.from('vx_questions').select('*').eq('assignment_id',assignmentId).order('question_number')]);if(ae||qe)setError((ae||qe).message);setAssignment(a||null);setQuestions(q||[])}
 useEffect(()=>{if(assignmentId)load()},[assignmentId]);
 useEffect(()=>{if(!assignmentId)return;try{const raw=localStorage.getItem(draftKey);if(raw){const saved=JSON.parse(raw);setDraft({...emptyDraft,...saved});setShow(true);setDraftRestored(true)}else{setDraft(emptyDraft);setDraftRestored(false)}}catch{setDraft(emptyDraft);setDraftRestored(false)}},[draftKey,assignmentId]);
 function saveDraft(name,value){setDraft(d=>{const next={...d,[name]:value};try{localStorage.setItem(draftKey,JSON.stringify(next))}catch{}return next})}
 function clearDraft(){try{localStorage.removeItem(draftKey)}catch{}setDraft(emptyDraft);setDraftRestored(false)}
 async function upload(file,folder){if(!file?.name)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`assignments/${assignmentId}/q${String(nextNo).padStart(2,'0')}/${folder}/${crypto.randomUUID()}-${safe}`;const {error}=await vx.storage.from(VX_BUCKET).upload(path,file,{upsert:false});if(error)throw error;return path}
 async function addQuestion(e){e.preventDefault();if(saving)return;const form=e.currentTarget;setSaving(true);setError('');try{const fd=new FormData(form),drawing=fd.get('drawing'),image=fd.get('modelImage');const drawingPath=await upload(drawing,'drawing'),imagePath=image?.name?await upload(image,'model'):null;const {error}=await vx.from('vx_questions').insert({assignment_id:assignmentId,question_number:nextNo,title:String(fd.get('title')||`Question ${nextNo}`).trim(),drawing_path:drawingPath,drawing_name:drawing?.name||null,model_image_path:imagePath,model_image_name:image?.name||null,show_model_preview:Boolean(imagePath)&&fd.get('preview')==='on',reference_volume:Number(fd.get('volume')).toFixed(3),reference_area:Number(fd.get('area')).toFixed(3),reference_mass:Number(fd.get('mass')).toFixed(3),reference_com_x:Number(fd.get('x')).toFixed(3),reference_com_y:Number(fd.get('y')).toFixed(3),reference_com_z:Number(fd.get('z')).toFixed(3)});if(error)throw error;clearDraft();form.reset();setShow(false);await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function openFile(path){if(!path)return;const {data,error}=await vx.storage.from(VX_BUCKET).createSignedUrl(path,300);if(error)return setError(error.message);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 async function toggle(q){const value=!q.show_model_preview;setQuestions(xs=>xs.map(x=>x.id===q.id?{...x,show_model_preview:value}:x));const {error}=await vx.from('vx_questions').update({show_model_preview:value,updated_at:new Date().toISOString()}).eq('id',q.id);if(error){setError(error.message);load()}}
 if(!assignment)return <main className="vx-page"><div className="vx-wrap"><div className="vx-empty">กำลังโหลด Assignment...</div></div></main>;
 return <main className="vx-page"><div className="vx-wrap"><header className="vx-top"><div><Link className="vx-file" href="/verifyx/teacher"><ArrowLeft size={15}/>Assignments</Link><p className="vx-kicker" style={{marginTop:14}}>ASSIGNMENT</p><h1>{assignment.title}</h1><p>{assignment.course||'ไม่ระบุวิชา'} · {assignment.max_attempts} attempts / ข้อ</p></div><button className="vx-btn primary" onClick={()=>setShow(v=>!v)}><Plus size={16}/>เพิ่มข้อ</button></header>
 {show&&<section className="vx-card"><h3>เพิ่มโจทย์ข้อ {nextNo}</h3>{draftRestored&&<div className="vx-success" style={{marginTop:12}}>กู้คืนข้อมูลที่พิมพ์ค้างไว้แล้ว · ไฟล์ PDF/รูปต้องเลือกใหม่</div>}<form className="vx-form" onSubmit={addQuestion}><label>ชื่อข้อ<input name="title" required value={draft.title} onChange={e=>saveDraft('title',e.target.value)}/></label><label>Drawing PDF<input name="drawing" type="file" accept="application/pdf,.pdf" required/></label><div className="vx-mass-grid"><label>Volume mm³<input name="volume" type="number" step="0.001" required value={draft.volume} onChange={e=>saveDraft('volume',e.target.value)}/></label><label>Surface Area mm²<input name="area" type="number" step="0.001" required value={draft.area} onChange={e=>saveDraft('area',e.target.value)}/></label><label>Mass g<input name="mass" type="number" step="0.001" required value={draft.mass} onChange={e=>saveDraft('mass',e.target.value)}/></label><label>COM X<input name="x" type="number" step="0.001" required value={draft.x} onChange={e=>saveDraft('x',e.target.value)}/></label><label>COM Y<input name="y" type="number" step="0.001" required value={draft.y} onChange={e=>saveDraft('y',e.target.value)}/></label><label>COM Z<input name="z" type="number" step="0.001" required value={draft.z} onChange={e=>saveDraft('z',e.target.value)}/></label></div><label>Model Reference Image<input name="modelImage" type="file" accept="image/png,image/jpeg,image/webp"/></label><label><span><input name="preview" type="checkbox" checked={draft.preview} onChange={e=>saveDraft('preview',e.target.checked)}/> แสดง Model Image ให้นักเรียนเห็น</span></label><div className="vx-toolbar"><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึกโจทย์'}</button><button type="button" className="vx-btn secondary" disabled={saving} onClick={clearDraft}>ล้างข้อมูลที่พิมพ์ค้าง</button></div></form></section>}
 {error&&<div className="vx-error">{error}</div>}
 <section className="vx-list">{questions.length?questions.map(q=><article className="vx-card vx-question" key={q.id}><div className="vx-top" style={{marginBottom:10}}><div><p className="vx-kicker">QUESTION {q.question_number}</p><h3>{q.title}</h3></div><span className="vx-status">พร้อมตรวจ</span></div><div className="vx-toolbar"><button className="vx-file" onClick={()=>openFile(q.drawing_path)}><FileText size={15}/>Drawing PDF</button>{q.model_image_path&&<button className="vx-file" onClick={()=>openFile(q.model_image_path)}><ImageIcon size={15}/>Model Image</button>}</div><div className="vx-tags"><span>V {Number(q.reference_volume).toFixed(3)}</span><span>A {Number(q.reference_area).toFixed(3)}</span><span>M {Number(q.reference_mass).toFixed(3)}</span><span>COM {Number(q.reference_com_x).toFixed(3)}, {Number(q.reference_com_y).toFixed(3)}, {Number(q.reference_com_z).toFixed(3)}</span></div>{q.model_image_path&&<button className="vx-btn secondary" style={{marginTop:12}} onClick={()=>toggle(q)}><Eye size={15}/>{q.show_model_preview?'นักเรียนเห็นรูป':'ซ่อนรูปจากนักเรียน'}</button>}</article>):<div className="vx-empty">ยังไม่มีโจทย์</div>}</section></div></main>
}
