'use client';

import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,Boxes,RefreshCw,LockKeyhole,UsersRound} from 'lucide-react';
import {vx} from '../../../vxClient';
import TeacherNav from '../../TeacherNav';

const diffLabel={basic:'Basic',pro:'Pro',advanced:'Advanced'};
const statusLabel={draft:'ฉบับร่าง',open:'เปิดรับงาน',closed:'ปิดรับงาน'};
const typeLabel={cad:'CAD / Engineering',mcq:'Multiple Choice',mixed:'CAD + Multiple Choice'};
const progressMeta={not_started:{label:'ยังไม่เริ่ม',cls:'vx-progress muted'},in_progress:{label:'กำลังทำ',cls:'vx-progress working'},final:{label:'Final แล้ว',cls:'vx-progress final'}};
const cadCategoryOptions=[['part_modeling','Part Modeling'],['assembly','Assembly'],['drawing','Drawing'],['sheet_metal','Sheet Metal'],['surface','Surface'],['other','Other']];
const cadCategoryLabel=Object.fromEntries(cadCategoryOptions);
const deriveType=(cad,mcq)=>cad>0&&mcq>0?'mixed':cad>0?'cad':'mcq';

export default function AssignmentDetail(){
 const {id}=useParams();const assignmentId=Number(id);
 const [assignment,setAssignment]=useState(null),[students,setStudents]=useState([]),[progress,setProgress]=useState([]),[finalRows,setFinalRows]=useState([]),[sections,setSections]=useState([]),[targetSections,setTargetSections]=useState([]),[team,setTeam]=useState([]);
 const [difficulty,setDifficulty]=useState('basic'),[cadCount,setCadCount]=useState(0),[mcqCount,setMcqCount]=useState(0),[subject,setSubject]=useState('SolidWorks'),[cadCategory,setCadCategory]=useState('part_modeling'),[cadLot,setCadLot]=useState(''),[mcqCategory,setMcqCategory]=useState(''),[randomize,setRandomize]=useState(true),[selectedSections,setSelectedSections]=useState([]);
 const [studentSearch,setStudentSearch]=useState(''),[studentStatus,setStudentStatus]=useState('all'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){
  setLoading(true);setError('');
  const [{data:a,error:ae},{data:st,error:se},{data:pr,error:pe},{data:fr,error:fre},{data:structure,error:ste},{data:maps,error:me},{data:t,error:te}]=await Promise.all([
   vx.from('vx_assignments').select('*').eq('id',assignmentId).single(),vx.rpc('vx_teacher_students'),vx.from('vx_student_assignment_progress').select('*').eq('assignment_id',assignmentId),vx.rpc('vx_teacher_final_results_v2'),vx.rpc('vx_teacher_academic_structure'),vx.from('vx_assignment_sections').select('section_id').eq('assignment_id',assignmentId),vx.rpc('vx_teacher_team')]);
  const err=ae||se||pe||fre||ste||me||te;if(err)setError(err.message);
  const asg=a||null;setAssignment(asg);setProgress(pr||[]);setTeam(t||[]);setFinalRows((fr||[]).filter(r=>Number(r.assignment_id)===assignmentId));
  const ss=Array.from(new Map((structure||[]).filter(x=>x.section_id&&x.section_active).map(x=>[Number(x.section_id),{id:Number(x.section_id),code:x.section_code,name:x.section_name,department:x.department_name}])).values());setSections(ss);
  const target=(maps||[]).map(x=>Number(x.section_id));setTargetSections(target);setSelectedSections(target);setStudents((st||[]).filter(s=>!target.length||target.includes(Number(s.section_id))));
  if(asg){setDifficulty(asg.difficulty||'basic');setCadCount(Number(asg.cad_question_count||0));setMcqCount(Number(asg.mcq_question_count||0));setSubject(asg.mcq_subject||'SolidWorks');setCadCategory(asg.cad_category||'part_modeling');setCadLot(asg.cad_lot||'');setMcqCategory(asg.mcq_category_code||'');setRandomize(asg.randomize_questions!==false)}setLoading(false)
 }
 useEffect(()=>{if(assignmentId)load()},[assignmentId]);
 const hasStarted=progress.length>0;
 const owner=useMemo(()=>team.find(x=>x.user_id===assignment?.created_by)||null,[team,assignment]);
 const sectionMap=useMemo(()=>Object.fromEntries(sections.map(s=>[s.id,s])),[sections]);
 const progressMap=useMemo(()=>Object.fromEntries(progress.map(p=>[String(p.student_id),p])),[progress]);
 const finalAgg=useMemo(()=>{const m={};finalRows.forEach(r=>{const k=String(r.student_id);if(!m[k])m[k]={scores:[],cad:[],mcq:[]};const sc=Number(r.score||0);m[k].scores.push(sc);if(r.question_type==='cad')m[k].cad.push(sc);if(r.question_type==='mcq')m[k].mcq.push(sc)});Object.values(m).forEach(x=>{const avg=z=>z.length?Math.round(z.reduce((a,b)=>a+b,0)/z.length):null;x.avg=avg(x.scores)||0;x.cadAvg=avg(x.cad);x.mcqAvg=avg(x.mcq)});return m},[finalRows]);
 const studentRows=useMemo(()=>students.map(s=>{const p=progressMap[String(s.student_id)],f=finalAgg[String(s.student_id)];return {...s,status:p?.status||'not_started',flagged_count:p?.flagged_count||0,final_score:f?.avg??null,cad_score:f?.cadAvg??null,mcq_score:f?.mcqAvg??null}}),[students,progressMap,finalAgg]);
 const visibleStudents=useMemo(()=>{const q=studentSearch.toLowerCase().trim();return studentRows.filter(s=>(studentStatus==='all'||s.status===studentStatus)&&(!q||`${s.full_name} ${s.student_code}`.toLowerCase().includes(q)))},[studentRows,studentSearch,studentStatus]);
 const stats=useMemo(()=>{const scores=studentRows.filter(x=>x.final_score!==null).map(x=>Number(x.final_score));return {total:studentRows.length,not_started:studentRows.filter(x=>x.status==='not_started').length,in_progress:studentRows.filter(x=>x.status==='in_progress').length,final:studentRows.filter(x=>x.status==='final').length,average:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0}},[studentRows]);
 const total=Number(cadCount||0)+Number(mcqCount||0);
 async function poolInfo(){const {data,error}=await vx.rpc('vx_teacher_assignment_pool_info_v3',{p_difficulty:difficulty,p_subject:subject||'SolidWorks',p_mcq_category_code:mcqCategory||'',p_cad_category:cadCategory||'',p_cad_lot:cadLot||''});if(error)throw error;const x=data?.[0]||{};return {cad:Number(x.cad_family_count||0),variants:Number(x.cad_variant_count||0),mcq:Number(x.mcq_question_count||0)}}
 async function validateReadiness(){if(total<1)throw new Error('Assignment ต้องมีอย่างน้อย 1 ข้อ');if(sections.length>0&&selectedSections.length===0)throw new Error('กรุณาเลือกอย่างน้อย 1 Section');const pool=await poolInfo();if(cadCount>pool.cad)throw new Error(`CAD Bank ตามตัวกรองนี้พร้อมใช้ ${pool.cad} Family แต่ Assignment ต้องการ ${cadCount} ข้อ · เพิ่ม Drawing PDF/เปิดใช้ Variant ให้เพียงพอก่อน`);if(mcqCount>pool.mcq)throw new Error(`MCQ Bank ตามตัวกรองนี้พร้อมใช้ ${pool.mcq} ข้อ แต่ Assignment ต้องการ ${mcqCount} ข้อ`);return pool}
 async function saveRules(e){e.preventDefault();if(hasStarted||saving)return;setSaving(true);setError('');setMessage('');try{await validateReadiness();const type=deriveType(cadCount,mcqCount);const {error}=await vx.from('vx_assignments').update({difficulty,question_count:total,assignment_type:type,question_category:type==='mcq'?'mcq':cadCategory||'part_modeling',cad_question_count:cadCount,mcq_question_count:mcqCount,mcq_subject:subject||'SolidWorks',mcq_category_code:mcqCategory.trim(),cad_category:cadCategory,cad_lot:cadLot.trim(),randomize_questions:randomize,updated_at:new Date().toISOString()}).eq('id',assignmentId);if(error)throw error;if(sections.length>0){const {error:mapErr}=await vx.rpc('vx_teacher_set_assignment_sections',{p_assignment_id:assignmentId,p_section_ids:selectedSections});if(mapErr)throw mapErr}setMessage('บันทึกกติกาและแหล่งโจทย์แล้ว');await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function setStatus(status){if(saving)return;setSaving(true);setError('');setMessage('');try{if(status==='open')await validateReadiness();const {error}=await vx.from('vx_assignments').update({status,updated_at:new Date().toISOString()}).eq('id',assignmentId);if(error)throw error;setMessage(`เปลี่ยนสถานะเป็น ${statusLabel[status]} แล้ว`);await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 function toggleSection(id){setSelectedSections(xs=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id])}
 if(loading)return <main className="vx-page"><div className="vx-wrap"><div className="vx-empty">กำลังโหลด Assignment...</div></div></main>;
 if(!assignment)return <main className="vx-page"><div className="vx-wrap"><div className="vx-error">ไม่พบ Assignment หรือคุณไม่มีสิทธิ์เข้าถึง</div></div></main>;
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="assignments"/>
  <header className="vx-top"><div><Link className="vx-file" href="/verifyx/teacher"><ArrowLeft size={15}/>Assignments</Link><p className="vx-kicker" style={{marginTop:14}}>ASSIGNMENT DETAIL</p><h1>{assignment.title}</h1><p>{assignment.course||'ไม่ระบุวิชา'} · {statusLabel[assignment.status]||assignment.status}</p><div className="vx-tags"><span>{typeLabel[assignment.assignment_type]||assignment.assignment_type}</span><span>{diffLabel[assignment.difficulty]}</span><span>ครู {owner?.display_name||'—'}</span>{Number(assignment.cad_question_count||0)>0&&<><span>{cadCategoryLabel[assignment.cad_category]||assignment.cad_category||'CAD'}</span>{assignment.cad_lot&&<span>Lot {assignment.cad_lot}</span>}</>}{Number(assignment.mcq_question_count||0)>0&&assignment.mcq_category_code&&<span>MCQ {assignment.mcq_category_code}</span>}{targetSections.length?targetSections.map(x=><span key={x}>Section {sectionMap[x]?.name||x}</span>):<span>Legacy · ทั้งโรงเรียน</span>}</div></div><div className="vx-toolbar"><button className="vx-btn secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><Link className="vx-btn secondary" href="/verifyx/teacher/question-bank"><Boxes size={15}/>Question Bank</Link></div></header>
  {message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
  <section className="vx-grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',marginBottom:14}}><div className="vx-card"><small>นักเรียนเป้าหมาย</small><h2>{stats.total}</h2></div><div className="vx-card"><small>ยังไม่เริ่ม</small><h2>{stats.not_started}</h2></div><div className="vx-card"><small>กำลังทำ</small><h2>{stats.in_progress}</h2></div><div className="vx-card"><small>Final</small><h2>{stats.final}</h2></div><div className="vx-card"><small>คะแนนเฉลี่ย</small><h2>{stats.average}/100</h2></div></section>
  <section className="vx-card" style={{marginBottom:14}}><div className="vx-top"><div><p className="vx-kicker">RULES</p><h2>กติกา Assignment</h2><p>{hasStarted?'มีนักเรียนเริ่มแล้ว กติกา แหล่งโจทย์ และ Section ถูกล็อก':'แก้จำนวนข้อและแหล่งโจทย์ได้จนกว่าจะมีนักเรียนเริ่ม'}</p></div>{hasStarted?<span className="vx-progress working"><LockKeyhole size={13}/>Locked</span>:<span className="vx-progress final">Editable</span>}</div>
   <form className="vx-form" onSubmit={saveRules}><div className="vx-form-row"><label>Difficulty<select value={difficulty} disabled={hasStarted} onChange={e=>setDifficulty(e.target.value)}><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label><label>Subject สำหรับปรนัย<input value={subject} disabled={hasStarted} onChange={e=>setSubject(e.target.value)}/></label></div><div className="vx-form-row"><label>CAD / Mass Properties<input type="number" min="0" value={cadCount} disabled={hasStarted} onChange={e=>setCadCount(Math.max(0,Number(e.target.value)||0))}/></label><label>ปรนัย<input type="number" min="0" value={mcqCount} disabled={hasStarted} onChange={e=>setMcqCount(Math.max(0,Number(e.target.value)||0))}/></label></div>
   <div className="vx-card" style={{padding:14}}><p className="vx-kicker">QUESTION SOURCE</p><div className="vx-form-row"><label>CAD Category<select value={cadCategory} disabled={hasStarted} onChange={e=>setCadCategory(e.target.value)}>{cadCategoryOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>CAD Lot<input value={cadLot} disabled={hasStarted} onChange={e=>setCadLot(e.target.value)} placeholder="ว่าง = ทุก Lot"/></label></div><label>MCQ Category Code<input value={mcqCategory} disabled={hasStarted} onChange={e=>setMcqCategory(e.target.value.toUpperCase())} placeholder="ว่าง = ทุก Category"/></label><div className="vx-tags"><span>CAD {cadCount}</span><span>ปรนัย {mcqCount}</span><span><b>รวม {total} ข้อ</b></span></div></div>
   {sections.length>0&&<div><p className="vx-kicker" style={{marginTop:12}}>TARGET SECTION</p><div className="vx-list">{sections.map(s=><label key={s.id} className="vx-card" style={{padding:11,display:'flex',gap:9,alignItems:'center',cursor:hasStarted?'default':'pointer'}}><input type="checkbox" checked={selectedSections.includes(s.id)} disabled={hasStarted} onChange={()=>toggleSection(s.id)}/><span><b>{s.department} · {s.name}</b> <small>({s.code})</small></span></label>)}</div></div>}
   <label className="vx-checkline"><input type="checkbox" checked={randomize} disabled={hasStarted} onChange={e=>setRandomize(e.target.checked)}/><span>สุ่ม Family/Variant/ข้อปรนัย และสลับตัวเลือกปรนัย</span></label><button className="vx-btn primary" disabled={hasStarted||saving||total<1}>{saving?'กำลังตรวจคลัง...':'บันทึกกติกา'}</button></form>
   <div className="vx-toolbar" style={{marginTop:12}}>{assignment.status!=='open'&&<button className="vx-link secondary" disabled={saving} onClick={()=>setStatus('open')}>เปิดรับงาน</button>}{assignment.status==='open'&&<button className="vx-link secondary" disabled={saving} onClick={()=>setStatus('closed')}>ปิดรับงาน</button>}</div>
  </section>
  <section className="vx-card"><div className="vx-top"><div><p className="vx-kicker">STUDENTS</p><h2>นักเรียนใน Assignment นี้</h2><p>แสดงเฉพาะนักเรียนใน Section เป้าหมาย</p></div><UsersRound size={22}/></div><div className="vx-form"><div className="vx-form-row"><label>ค้นหา<input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="ชื่อหรือรหัสนักเรียน"/></label><label>สถานะ<select value={studentStatus} onChange={e=>setStudentStatus(e.target.value)}><option value="all">ทั้งหมด</option><option value="not_started">ยังไม่เริ่ม</option><option value="in_progress">กำลังทำ</option><option value="final">Final แล้ว</option></select></label></div></div><div className="vx-list">{visibleStudents.length?visibleStudents.map(s=>{const meta=progressMeta[s.status];return <article className="vx-item" key={s.student_id}><div><h3>{s.full_name}</h3><p>{s.student_code}{s.section_id?` · ${sectionMap[Number(s.section_id)]?.name||'Section'}`:''}</p><div className="vx-tags">{s.status==='in_progress'&&s.flagged_count>0&&<span>🟨 มาร์กไว้ {s.flagged_count}</span>}{s.status==='final'&&<><span>รวม {s.final_score??0}/100</span>{s.cad_score!==null&&<span>CAD {s.cad_score}</span>}{s.mcq_score!==null&&<span>ปรนัย {s.mcq_score}</span>}</>}</div></div><span className={meta.cls}>{meta.label}</span></article>}):<div className="vx-empty">ไม่พบนักเรียนในกลุ่มเป้าหมาย</div>}</div></section>
 </div></main>;
}
