'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {BookOpen,Library,UsersRound,BarChart3,School,SlidersHorizontal,UserCircle,LockKeyhole,LogOut,ShieldCheck,Users} from 'lucide-react';
import {vx} from '../vxClient';
import './teacher-ui.css';

const PENDING_KEY='vx-pending-school-onboarding';
const nav=[
 ['/verifyx/teacher','Assignments',BookOpen],
 ['/verifyx/teacher/question-bank','Question Bank',Library],
 ['/verifyx/teacher/students','Students',UsersRound],
 ['/verifyx/teacher/results','Results',BarChart3],
 ['/verifyx/teacher/school-profile','School Profile',School],
 ['/verifyx/teacher/settings','Settings',SlidersHorizontal],
 ['/verifyx/teacher/profile','Profile',UserCircle]
];

export default function TeacherLayout({children}){
 const pathname=usePathname();
 const [loading,setLoading]=useState(true),[session,setSession]=useState(null),[isTeacher,setIsTeacher]=useState(false),[mode,setMode]=useState('login'),[message,setMessage]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(null);
 async function refresh(nextSession){setLoading(true);setError('');const s=nextSession??(await vx.auth.getSession()).data.session;setSession(s||null);let teacher=false;if(s){const first=await vx.rpc('vx_me_is_teacher');if(first.error)setError(first.error.message);else teacher=Boolean(first.data);if(!teacher){const displayName=s.user?.user_metadata?.display_name||s.user?.user_metadata?.full_name||'';const joined=await vx.rpc('vx_accept_teacher_invite',{p_display_name:displayName});if(!joined.error&&joined.data){const again=await vx.rpc('vx_me_is_teacher');teacher=Boolean(again.data)}}}setIsTeacher(teacher);try{setPending(JSON.parse(localStorage.getItem(PENDING_KEY)||'null'))}catch{setPending(null)}setLoading(false)}
 async function revalidateAccess(){const s=(await vx.auth.getSession()).data.session;if(!s){setSession(null);setIsTeacher(false);return}const {data,error}=await vx.rpc('vx_me_is_teacher');if(error||!data){setSession(s);setIsTeacher(false);if(error)setError(error.message)}}
 useEffect(()=>{refresh();const {data:{subscription}}=vx.auth.onAuthStateChange((_e,s)=>refresh(s));const onFocus=()=>revalidateAccess();const onVisible=()=>{if(document.visibilityState==='visible')revalidateAccess()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisible);return()=>{subscription.unsubscribe();window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisible)}},[]);
 async function signIn(e){e.preventDefault();setError('');setMessage('');const fd=new FormData(e.currentTarget);const {error}=await vx.auth.signInWithPassword({email:String(fd.get('email')).trim(),password:String(fd.get('password'))});if(error)setError(error.message)}
 async function createSchoolTeacher(form,s){const {data:ok,error}=await vx.rpc('vx_create_school_teacher',{p_display_name:form.displayName,p_institution_name:form.schoolName,p_institution_code:form.schoolCode});if(error){setError(error.message);return}if(ok){localStorage.removeItem(PENDING_KEY);setPending(null);setMessage('สร้างโรงเรียนและบัญชีครูเรียบร้อย');await refresh(s||session)}}
 async function signUpSchool(e){e.preventDefault();setError('');setMessage('');const fd=new FormData(e.currentTarget);const form={displayName:String(fd.get('displayName')||'').trim(),schoolName:String(fd.get('schoolName')||'').trim(),schoolCode:String(fd.get('schoolCode')||'').trim().toUpperCase()};const email=String(fd.get('email')).trim(),password=String(fd.get('password'));if(!/^[A-Z0-9_-]{3,24}$/.test(form.schoolCode)){setError('School Code ใช้ A-Z, 0-9, _ หรือ - ความยาว 3-24 ตัว');return}const {data,error}=await vx.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/verifyx/teacher`,data:{display_name:form.displayName}}});if(error){setError(error.message);return}localStorage.setItem(PENDING_KEY,JSON.stringify(form));setPending(form);if(data.session)await createSchoolTeacher(form,data.session);else setMessage('สร้างบัญชีแล้ว กรุณายืนยัน Email แล้วกลับมาหน้านี้')}
 async function signUpInvited(e){e.preventDefault();setError('');setMessage('');const fd=new FormData(e.currentTarget);const displayName=String(fd.get('displayName')).trim(),email=String(fd.get('email')).trim(),password=String(fd.get('password'));const {data,error}=await vx.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/verifyx/teacher`,data:{display_name:displayName}}});if(error){setError(error.message);return}if(data.session){const joined=await vx.rpc('vx_accept_teacher_invite',{p_display_name:displayName});if(joined.error)setError(joined.error.message);else await refresh(data.session)}else setMessage('สมัครแล้ว กรุณายืนยัน Email ระบบจะเข้าร่วมโรงเรียนที่เชิญไว้อัตโนมัติ')}
 async function finishOnboarding(e){e.preventDefault();const fd=new FormData(e.currentTarget);await createSchoolTeacher({displayName:String(fd.get('displayName')).trim(),schoolName:String(fd.get('schoolName')).trim(),schoolCode:String(fd.get('schoolCode')).trim().toUpperCase()},session)}
 async function signOut(){await vx.auth.signOut()}
 const isActive=href=>href==='/verifyx/teacher'?pathname==='/verifyx/teacher':pathname?.startsWith(href);
 if(loading)return <main className="vx-page"><div className="vx-wrap"><div className="vx-empty">กำลังตรวจสอบสิทธิ์ครู...</div></div></main>;
 if(!session)return <main className="vx-page"><div className="vx-wrap"><section className="vx-card vx-login"><div className="vx-logo">VX</div><p className="vx-kicker" style={{marginTop:14}}>TEACHER ACCESS</p><h2>{mode==='school'?'Create School Account':mode==='join'?'Join Invited School':'Teacher Login'}</h2>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}{mode==='login'&&<form className="vx-form" onSubmit={signIn}><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label><button className="vx-btn primary"><LockKeyhole size={16}/>Login</button></form>}{mode==='school'&&<form className="vx-form" onSubmit={signUpSchool}><label>ชื่อครู<input name="displayName" required/></label><label>ชื่อโรงเรียน / สถาบัน<input name="schoolName" required/></label><label>School Code<input name="schoolCode" maxLength={24} required/></label><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength="8" required/></label><button className="vx-btn primary"><School size={16}/>สร้างโรงเรียนและบัญชีครู</button></form>}{mode==='join'&&<form className="vx-form" onSubmit={signUpInvited}><label>ชื่อครู<input name="displayName" required/></label><label>Email ที่ได้รับเชิญ<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength="8" required/></label><button className="vx-btn primary"><Users size={16}/>สมัครและเข้าร่วมโรงเรียน</button></form>}<div className="vx-toolbar" style={{marginTop:12}}><button className="vx-btn secondary" onClick={()=>setMode('login')}>Login</button><button className="vx-btn secondary" onClick={()=>setMode('school')}>โรงเรียนใหม่</button><button className="vx-btn secondary" onClick={()=>setMode('join')}>ได้รับคำเชิญ</button></div><Link className="vx-file" href="/verifyx">กลับหน้า VerifyX</Link></section></div></main>;
 if(!isTeacher){const p=pending||{displayName:'',schoolName:'',schoolCode:''};return <main className="vx-page"><div className="vx-wrap"><section className="vx-card vx-login"><ShieldCheck size={30}/><h2>{pending?'ตั้งค่าโรงเรียนให้เสร็จ':'ไม่มีสิทธิ์ Teacher แล้ว'}</h2>{pending?<form className="vx-form" onSubmit={finishOnboarding}><label>ชื่อครู<input name="displayName" defaultValue={p.displayName} required/></label><label>ชื่อโรงเรียน<input name="schoolName" defaultValue={p.schoolName} required/></label><label>School Code<input name="schoolCode" defaultValue={p.schoolCode} required/></label><button className="vx-btn primary">สร้างโรงเรียน</button></form>:<p>บัญชีนี้ไม่ได้อยู่ใน Teacher Team ปัจจุบัน</p>}<button className="vx-btn secondary" onClick={signOut}>Logout</button></section></div></main>}
 return <><header className="vx-teacherbar"><div className="vx-teacherbar-inner"><Link href="/verifyx/teacher" className="vx-shell-brand"><span className="vx-shell-mark">VX</span><span><b>VerifyX</b><small>Teacher</small></span></Link><nav className="vx-shell-nav">{nav.map(([href,label,Icon])=><Link key={href} href={href} className={isActive(href)?'active':''}><Icon size={15}/><span>{label}</span></Link>)}</nav><button className="vx-shell-logout" onClick={signOut} title="Logout"><LogOut size={15}/><span>Logout</span></button></div></header>{children}</>;
}
