'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Plus,Trash2,BookOpen,UsersRound,LockKeyhole,ChevronRight} from 'lucide-react';
import {vx} from '../vxClient';
import TeacherNav from './TeacherNav';

const statusLabel={draft:'ฉบับร่าง',open:'เปิดรับงาน',closed:'ปิดรับงาน'};
const diffLabel={basic:'Basic',pro:'Pro',advanced:'Advanced'};
const typeLabel={cad:'CAD / Engineering',mcq:'Multiple Choice',mixed:'Mixed: CAD + MCQ'};

export default function TeacherPage(){
 const [items,setItems]=useState([]),[startedAssignments,setStartedAssignments]=useState(new Set()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[busyId,setBusyId]=useState(null),[assignmentType,setAssignmentType]=useState('cad');
 const submitLock=useRef(false);
 async function load(){setLoading(true);setError('');const [{data,error},{data:pr,error:pe}]=await Promise.all([vx.from('vx_assignments').select('*, vx_questions(count)').order('created_at',{ascending:false}),vx.from('vx_student_assignment_progress').select('assignment_id')]);if(error||pe)setError((error||pe).message);setItems(data||[]);setStartedAssignments(new Set((pr||[]).map(x=>Number(x.assignment_id))));setLoading(false)}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>({total:items.length,open:items.filter(x=>x.status==='open').length,draft:items.filter(x=>x.status==='draft').length,locked:items.filter(x=>startedAssignments.has(Number(x.id))).length}),[items,startedAssignments]);
 async function getPoolInfo(difficulty,subject='SolidWorks',category=''){const {data,error}=await vx.rpc('vx_teacher_assignment_pool_info',{p_difficulty:difficulty,p_subject:subject,p_category_code:category});if(error)throw error;const x=data?.[0]||{};return {cad:Number(x.cad_family_count||0),variants:Number(x.cad_variant_count||0),mcq:Number(x.mcq_question_count||0)}}
 async function ensurePool({type,difficulty,cadCount,mcqCount,subject='SolidWorks',category=''}){const pool=await getPoolInfo(difficulty,subject,category);if((type==='cad'||type==='mixed')&&pool.cad<cadCount)throw new Error(`CAD Bank ระดับ ${diffLabel[difficulty]||difficulty} มี Family พร้อมใช้ ${pool.cad} Family แต่ต้องการ ${cadCount} ข้อ`);if((type==='mcq'||type==='mixed')&&pool.mcq<mcqCount)throw new Error(`MCQ Bank ${subject} ระดับ ${diffLabel[difficulty]||difficulty} มี ${pool.mcq} ข้อ แต่ต้องการ ${mcqCount} ข้อ`);return pool}
 async function create(e){e.preventDefault();if(submitLock.current)return;submitLock.current=true;setSaving(true);setError('');setMessage('');const form=e.currentTarget;const fd=new FormData(form);try{const type=String(fd.get('assignmentType')||'cad');const difficulty=String(fd.get('difficulty')||'basic');const cadCount=type==='mcq'?0:Number(fd.get('cadCount')||0);const mcqCount=type==='cad'?0:Number(fd.get('mcqCount')||0);const total=cadCount+mcqCount;const subject=String(fd.get('mcqSubject')||'SolidWorks').trim()||'SolidWorks';if(total<1)throw new Error('กรุณากำหนดจำนวนข้ออย่างน้อย 1 ข้อ');await ensurePool({type,difficulty,cadCount,mcqCount,subject});const {error}=await vx.from('vx_assignments').insert({title:String(fd.get('title')||'').trim(),course:String(fd.get('course')||'').trim(),description:String(fd.get('description')||'').trim(),status:fd.get('status')||'draft',max_attempts:1,question_category:type==='cad'?'part_modeling':type,difficulty,question_count:total,randomize_questions:fd.get('randomize')==='on',assignment_type:type,cad_question_count:cadCount,mcq_question_count:mcqCount,mcq_subject:subject,mcq_category_code:''});if(error)throw error;form.reset();setAssignmentType('cad');setShow(false);setMessage(`สร้าง Assignment ${typeLabel[type]} เรียบร้อยแล้ว`);await load();window.scrollTo({top:0,behavior:'smooth'})}catch(err){setError(err.message)}finally{setSaving(false);submitLock.current=false}}
 async function setStatus(a,status){setBusyId(a.id);setError('');setMessage('');try{if(status==='open')await ensurePool({type:a.assignment_type||'cad',difficulty:a.difficulty||'basic',cadCount:Number(a.cad_question_count??a.question_count??1),mcqCount:Number(a.mcq_question_count||0),subject:a.mcq_subject||'SolidWorks',category:a.mcq_category_code||''});const {error}=await vx.from('vx_assignments').update({status,updated_at:new Date().toISOString()}).eq('id',a.id);if(error)throw error;setMessage(`เปลี่ยน “${a.title}” เป็น ${statusLabel[status]} แล้ว`);await load()}catch(err){setError(err.message)}finally{setBusyId(null)}}
 async function removeEmpty(a){if(startedAssignments.has(Number(a.id)))return setError('Assignment นี้มีประวัตินักเรียนแล้ว ห้ามลบ ให้ปิดรับงานแทน');const count=a.vx_questions?.[0]?.count||0;if(count>0)return setError('Assignment ที่มีโจทย์เดิมแล้วต้องลบโจทย์ก่อน');if(!window.confirm(`ลบ “${a.title}” ใช่ไหม?`))return;setBusyId(a.id);setError('');setMessage('');const {error}=await vx.from('vx_assignments').delete().eq('id',a.id);setBusyId(null);if(error)return setError(error.message);setMessage('ลบ Assignment แล้ว');load()}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="assignments"/>
  <section className="vx-dashboard-head"><div><Link className="vx-file" href="/verifyx"><ArrowLeft size={15}/>VerifyX</Link><p className="vx-kicker" style={{marginTop:14}}>TEACHER MODE</p><h1>Assignments</h1><p>สร้างงานจาก CAD Bank และ Multiple Choice Bank ในที่เดียว</p></div><button className="vx-btn primary vx-create-btn" onClick={()=>setShow(v=>!v)}><Plus size={17}/>{show?'ปิดฟอร์ม':'สร้าง Assignment'}</button></section>
  <section className="vx-overview-strip"><div><small>ทั้งหมด</small><strong>{stats.total}</strong></div><div><small>เปิดรับงาน</small><strong>{stats.open}</strong></div><div><small>ฉบับร่าง</small><strong>{stats.draft}</strong></div><div><small>มีประวัตินักเรียน</small><strong>{stats.locked}</strong></div></section>
  {message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
  {show&&<section className="vx-card vx-create-panel"><div className="vx-section-title"><div><p className="vx-kicker">NEW ASSIGNMENT</p><h2>สร้าง Assignment ใหม่</h2></div></div><form className="vx-form" onSubmit={create}><div className="vx-form-row"><label>ชื่อ Assignment<input name="title" required placeholder="เช่น การบ้าน #02"/></label><label>วิชา / Course<input name="course" placeholder="เช่น Drawing 001"/></label></div><label>คำอธิบาย<textarea name="description" rows="3" placeholder="รายละเอียดงานหรือคำแนะนำเพิ่มเติม"/></label><div className="vx-form-row"><label>ชนิด Assignment<select name="assignmentType" value={assignmentType} onChange={e=>setAssignmentType(e.target.value)}><option value="cad">CAD / Engineering</option><option value="mcq">Multiple Choice</option><option value="mixed">Mixed: CAD + MCQ</option></select></label><label>ระดับ<select name="difficulty" defaultValue="basic"><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label></div>{assignmentType!=='mcq'&&<label>จำนวนข้อ CAD<input name="cadCount" type="number" min="1" defaultValue="3" required/></label>}{assignmentType!=='cad'&&<div className="vx-form-row"><label>จำนวนข้อปรนัย<input name="mcqCount" type="number" min="1" defaultValue="5" required/></label><label>MCQ Subject<input name="mcqSubject" defaultValue="SolidWorks"/></label></div>}<div className="vx-form-row"><label>สถานะ<select name="status" defaultValue="draft"><option value="draft">ฉบับร่าง</option><option value="open">เปิดรับงาน</option><option value="closed">ปิดรับงาน</option></select></label><label className="vx-checkline"><input name="randomize" type="checkbox" defaultChecked/><span>สุ่มโจทย์ให้นักเรียน</span></label></div><div className="vx-empty" style={{marginTop:0}}>ระบบจะตรวจจำนวนโจทย์จาก School Central Question Bank ก่อนสร้างและก่อนเปิดรับงาน</div><button className="vx-btn primary" disabled={saving}>{saving?'กำลังตรวจคลังโจทย์...':'บันทึก Assignment'}</button></form></section>}
  {loading?<div className="vx-empty">กำลังโหลด...</div>:<section className="vx-assignment-grid">{items.length?items.map(a=>{const oldCount=a.vx_questions?.[0]?.count||0;const hasHistory=startedAssignments.has(Number(a.id));const type=a.assignment_type||'cad';return <article className="vx-assignment-card" key={a.id}><div className="vx-assignment-main"><div className="vx-assignment-icon"><BookOpen size={20}/></div><div className="vx-assignment-copy"><div className="vx-assignment-title-row"><h3>{a.title}</h3><span className={`vx-assignment-status ${a.status}`}>{statusLabel[a.status]||a.status}</span></div><p>{a.course||'ไม่ระบุวิชา'}</p><div className="vx-assignment-meta"><span>{typeLabel[type]||type}</span><span>{diffLabel[a.difficulty]||a.difficulty}</span>{Number(a.cad_question_count||0)>0&&<span>CAD {a.cad_question_count}</span>}{Number(a.mcq_question_count||0)>0&&<span>MCQ {a.mcq_question_count}</span>}<span>รวม {a.question_count} ข้อ</span><span>{a.randomize_questions?'สุ่มโจทย์':'ไม่สุ่ม'}</span>{hasHistory&&<span><LockKeyhole size={12}/>ล็อกกติกาแล้ว</span>}</div></div></div><div className="vx-assignment-footer"><div className="vx-assignment-note">{hasHistory?<><UsersRound size={14}/>มีนักเรียนเริ่มงานแล้ว</>:<><UsersRound size={14}/>ยังไม่มีประวัตินักเรียน</>}</div><div className="vx-assignment-actions">{a.status!=='open'&&<button className="vx-link secondary" disabled={busyId===a.id} onClick={()=>setStatus(a,'open')}>เปิดรับงาน</button>}{a.status==='open'&&<button className="vx-link secondary" disabled={busyId===a.id} onClick={()=>setStatus(a,'closed')}>ปิดรับงาน</button>}<Link className="vx-link primary" href={`/verifyx/teacher/assignment/${a.id}`}>จัดการ<ChevronRight size={15}/></Link>{!hasHistory&&oldCount===0&&<button className="vx-icon-btn danger" title="ลบ" disabled={busyId===a.id} onClick={()=>removeEmpty(a)}><Trash2 size={15}/></button>}</div></div></article>}):<div className="vx-empty">ยังไม่มี Assignment</div>}</section>}
 </div></main>
}
