'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Plus,Trash2,BookOpen,UsersRound,LockKeyhole,ChevronRight} from 'lucide-react';
import {vx} from '../vxClient';
import TeacherNav from './TeacherNav';

const statusLabel={draft:'ฉบับร่าง',open:'เปิดรับงาน',closed:'ปิดรับงาน'};
const diffLabel={basic:'Basic',pro:'Pro',advanced:'Advanced'};
const typeLabel={cad:'CAD / Engineering',mcq:'Multiple Choice',mixed:'CAD + Multiple Choice'};
const cadCategoryOptions=[['part_modeling','Part Modeling'],['assembly','Assembly'],['drawing','Drawing'],['sheet_metal','Sheet Metal'],['surface','Surface'],['other','Other']];
const cadCategoryLabel=Object.fromEntries(cadCategoryOptions);

export default function TeacherPage(){
 const [items,setItems]=useState([]),[startedAssignments,setStartedAssignments]=useState(new Set()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[busyId,setBusyId]=useState(null);
 const [cadCounts,setCadCounts]=useState({part_modeling:3,assembly:0,drawing:0}),[mcqCount,setMcqCount]=useState(0),[cadLot,setCadLot]=useState(''),[mcqCategory,setMcqCategory]=useState(''),[sections,setSections]=useState([]),[selectedSections,setSelectedSections]=useState([]),[assignmentSections,setAssignmentSections]=useState({}),[teacherTeam,setTeacherTeam]=useState([]);
 const submitLock=useRef(false);
 async function load(){
  setLoading(true);setError('');
  const [{data,error},{data:pr,error:pe},{data:structure,error:se},{data:maps,error:me},{data:team,error:te}]=await Promise.all([
   vx.from('vx_assignments').select('*, vx_questions(count)').order('created_at',{ascending:false}),
   vx.from('vx_student_assignment_progress').select('assignment_id'),
   vx.rpc('vx_teacher_academic_structure'),
   vx.from('vx_assignment_sections').select('assignment_id,section_id'),
   vx.rpc('vx_teacher_team')
  ]);
  if(error||pe||se||me||te)setError((error||pe||se||me||te).message);
  setItems(data||[]);setStartedAssignments(new Set((pr||[]).map(x=>Number(x.assignment_id))));setTeacherTeam(team||[]);
  const ss=(structure||[]).filter(x=>x.section_id&&x.section_active).map(x=>({id:Number(x.section_id),code:x.section_code,name:x.section_name,department:x.department_name,year:x.academic_year,term:x.term}));
  setSections(Array.from(new Map(ss.map(x=>[x.id,x])).values()));
  const by={};(maps||[]).forEach(x=>{const k=Number(x.assignment_id);if(!by[k])by[k]=[];by[k].push(Number(x.section_id))});setAssignmentSections(by);setLoading(false)
 }
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>({total:items.length,open:items.filter(x=>x.status==='open').length,draft:items.filter(x=>x.status==='draft').length,locked:items.filter(x=>startedAssignments.has(Number(x.id))).length}),[items,startedAssignments]);
 const sectionMap=useMemo(()=>Object.fromEntries(sections.map(s=>[s.id,s])),[sections]);
 const teacherMap=useMemo(()=>Object.fromEntries(teacherTeam.map(t=>[t.user_id,t.display_name])),[teacherTeam]);
 const cadCount=Object.values(cadCounts).reduce((sum,n)=>sum+Math.max(0,Number(n)||0),0);
 const draftTotal=cadCount+Number(mcqCount||0);
 function setCadCategoryCount(category,value){setCadCounts(x=>({...x,[category]:Math.max(0,Number(value)||0)}))}
 function assignmentCadCounts(a){const raw=a?.cad_category_counts&&typeof a.cad_category_counts==='object'?a.cad_category_counts:{};const clean=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Math.max(0,Number(v)||0)]).filter(([,v])=>v>0));if(Object.keys(clean).length)return clean;const n=Math.max(0,Number(a?.cad_question_count)||0);return n?{[a?.cad_category||'part_modeling']:n}:{}}
 async function getPoolInfo({difficulty,subject='CrownCAD',mcqCategory='',cadCategory='part_modeling',cadLot=''}){const {data,error}=await vx.rpc('vx_teacher_assignment_pool_info_v3',{p_difficulty:difficulty,p_subject:subject,p_mcq_category_code:mcqCategory||'',p_cad_category:cadCategory||'',p_cad_lot:cadLot||''});if(error)throw error;const x=data?.[0]||{};return {cad:Number(x.cad_family_count||0),variants:Number(x.cad_variant_count||0),mcq:Number(x.mcq_question_count||0)}}
 async function ensurePool(x){for(const [category,rawCount] of Object.entries(x.cadCounts||{})){const need=Math.max(0,Number(rawCount)||0);if(!need)continue;const pool=await getPoolInfo({...x,cadCategory:category});if(need>pool.cad)throw new Error(`CAD Bank ${cadCategoryLabel[category]||category} มีโจทย์พร้อมใช้ ${pool.cad} ข้อ แต่ต้องการ ${need} ข้อ`)}if(Number(x.mcqCount||0)>0){const pool=await getPoolInfo({...x,cadCategory:'part_modeling'});if(Number(x.mcqCount||0)>pool.mcq)throw new Error(`MCQ Bank ตามตัวกรองนี้มี ${pool.mcq} ข้อ แต่ต้องการ ${x.mcqCount} ข้อ`)}return true}
 function deriveType(cad,mcq){if(cad>0&&mcq>0)return 'mixed';if(cad>0)return 'cad';return 'mcq'}
 function toggleSection(id){setSelectedSections(xs=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id])}
 async function create(e){
  e.preventDefault();if(submitLock.current)return;submitLock.current=true;setSaving(true);setError('');setMessage('');const form=e.currentTarget,fd=new FormData(form);
  try{
   const difficulty=String(fd.get('difficulty')||'basic'),normalizedCadCounts=Object.fromEntries(Object.entries(cadCounts).map(([k,v])=>[k,Math.max(0,Number(v)||0)]).filter(([,v])=>v>0)),cad=Object.values(normalizedCadCounts).reduce((s,n)=>s+n,0),mcq=Number(mcqCount||0),total=cad+mcq,subject=String(fd.get('subject')||'CrownCAD').trim()||'CrownCAD';
   if(total<1)throw new Error('กรุณากำหนดจำนวนข้ออย่างน้อย 1 ข้อ');if(sections.length>0&&selectedSections.length===0)throw new Error('กรุณาเลือกอย่างน้อย 1 Section ที่จะได้รับ Assignment');
   await ensurePool({difficulty,cadCounts:normalizedCadCounts,mcqCount:mcq,subject,mcqCategory,cadLot});const type=deriveType(cad,mcq),cadCats=Object.keys(normalizedCadCounts),primaryCadCategory=cadCats.length===1?cadCats[0]:'';
   const {data:created,error}=await vx.from('vx_assignments').insert({title:String(fd.get('title')||'').trim(),course:String(fd.get('course')||'').trim(),description:String(fd.get('description')||'').trim(),status:fd.get('status')||'draft',max_attempts:1,question_category:type==='mcq'?'mcq':primaryCadCategory||'mixed_cad',difficulty,question_count:total,randomize_questions:fd.get('randomize')==='on',assignment_type:type,cad_question_count:cad,cad_category_counts:normalizedCadCounts,mcq_question_count:mcq,mcq_subject:subject,mcq_category_code:mcqCategory.trim(),cad_category:primaryCadCategory,cad_lot:cadLot.trim()}).select('id').single();if(error)throw error;
   if(sections.length>0){const {error:mapErr}=await vx.rpc('vx_teacher_set_assignment_sections',{p_assignment_id:created.id,p_section_ids:selectedSections});if(mapErr)throw mapErr}
   form.reset();setCadCounts({part_modeling:3,assembly:0,drawing:0});setMcqCount(0);setCadLot('');setMcqCategory('');setSelectedSections([]);setShow(false);setMessage(`สร้าง Assignment ${typeLabel[type]||type} รวม ${total} ข้อเรียบร้อยแล้ว`);await load();window.scrollTo({top:0,behavior:'smooth'})
  }catch(err){setError(err.message)}finally{setSaving(false);submitLock.current=false}
 }
 async function setStatus(a,status){setBusyId(a.id);setError('');setMessage('');try{if(status==='open')await ensurePool({difficulty:a.difficulty||'basic',cadCounts:assignmentCadCounts(a),mcqCount:Number(a.mcq_question_count||0),subject:a.mcq_subject||'CrownCAD',mcqCategory:a.mcq_category_code||'',cadLot:a.cad_lot||''});const {error}=await vx.from('vx_assignments').update({status,updated_at:new Date().toISOString()}).eq('id',a.id);if(error)throw error;setMessage(`เปลี่ยน “${a.title}” เป็น ${statusLabel[status]} แล้ว`);await load()}catch(err){setError(err.message)}finally{setBusyId(null)}}
 async function removeEmpty(a){if(startedAssignments.has(Number(a.id)))return setError('Assignment นี้มีประวัตินักเรียนแล้ว ห้ามลบ ให้ปิดรับงานแทน');const count=a.vx_questions?.[0]?.count||0;if(count>0)return setError('Assignment ที่มีโจทย์เดิมแล้วต้องลบโจทย์ก่อน');if(!window.confirm(`ลบ “${a.title}” ใช่ไหม?`))return;setBusyId(a.id);const {error}=await vx.from('vx_assignments').delete().eq('id',a.id);setBusyId(null);if(error)return setError(error.message);setMessage('ลบ Assignment แล้ว');load()}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="assignments"/>
  <section className="vx-dashboard-head"><div><Link className="vx-file" href="/verifyx"><ArrowLeft size={15}/>VerifyX</Link><p className="vx-kicker" style={{marginTop:14}}>TEACHER MODE</p><h1>Assignments</h1><p>สร้างงานแบบ CAD, ปรนัย หรือ Mixed และกำหนดแหล่งโจทย์ได้ละเอียด</p></div><button className="vx-btn primary vx-create-btn" onClick={()=>setShow(v=>!v)}><Plus size={17}/>{show?'ปิดฟอร์ม':'สร้าง Assignment'}</button></section>
  <section className="vx-overview-strip"><div><small>ทั้งหมด</small><strong>{stats.total}</strong></div><div><small>เปิดรับงาน</small><strong>{stats.open}</strong></div><div><small>ฉบับร่าง</small><strong>{stats.draft}</strong></div><div><small>มีประวัตินักเรียน</small><strong>{stats.locked}</strong></div></section>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
  {show&&<section className="vx-card vx-create-panel"><p className="vx-kicker">NEW ASSIGNMENT</p><h2>สร้าง Assignment ใหม่</h2><form className="vx-form" onSubmit={create}>
   <div className="vx-form-row"><label>ชื่อ Assignment<input name="title" required placeholder="เช่น การบ้าน #02"/></label><label>วิชา / Course<input name="course" placeholder="เช่น Drawing 001"/></label></div><label>คำอธิบาย<textarea name="description" rows="3"/></label>
   <div className="vx-form-row"><label>ระดับ<select name="difficulty" defaultValue="basic"><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label><label>Subject สำหรับปรนัย<input name="subject" defaultValue="CrownCAD"/></label></div>
   <div className="vx-form-row"><label>CAD / Mass Properties<input value={cadCount} readOnly type="number" min="0"/></label><label>ปรนัย Multiple Choice<input value={mcqCount} onChange={e=>setMcqCount(Math.max(0,Number(e.target.value)||0))} type="number" min="0"/></label></div>
   <div className="vx-card" style={{padding:14}}><p className="vx-kicker">QUESTION SOURCE · CAD MIX</p><div className="vx-form-row"><label>Part Modeling<input value={cadCounts.part_modeling||0} onChange={e=>setCadCategoryCount('part_modeling',e.target.value)} type="number" min="0"/></label><label>Assembly<input value={cadCounts.assembly||0} onChange={e=>setCadCategoryCount('assembly',e.target.value)} type="number" min="0"/></label></div><div className="vx-form-row"><label>Drawing<input value={cadCounts.drawing||0} onChange={e=>setCadCategoryCount('drawing',e.target.value)} type="number" min="0"/></label><label>CAD Lot<input value={cadLot} onChange={e=>setCadLot(e.target.value)} placeholder="ว่าง = ทุก Lot"/></label></div><label>MCQ Category Code<input value={mcqCategory} onChange={e=>setMcqCategory(e.target.value.toUpperCase())} placeholder="ว่าง = ทุก Category"/></label><div className="vx-tags"><span>Part {cadCounts.part_modeling||0}</span><span>ASSY {cadCounts.assembly||0}</span><span>Drawing {cadCounts.drawing||0}</span><span>CAD {cadCount}</span><span>ปรนัย {mcqCount}</span><span><b>รวม {draftTotal} ข้อ</b></span></div></div>
   {sections.length>0?<div><p className="vx-kicker">TARGET SECTION</p><div className="vx-list">{sections.map(s=><label key={s.id} className="vx-card" style={{display:'flex',gap:10,alignItems:'center',padding:12,cursor:'pointer'}}><input type="checkbox" checked={selectedSections.includes(s.id)} onChange={()=>toggleSection(s.id)}/><span><b>{s.department} · {s.name}</b> <small>({s.code})</small></span></label>)}</div></div>:<div className="vx-empty">โรงเรียนยังไม่มี Section · Assignment นี้จะมองเห็นได้ทั้งโรงเรียน</div>}
   <div className="vx-form-row"><label>สถานะ<select name="status" defaultValue="draft"><option value="draft">ฉบับร่าง</option><option value="open">เปิดรับงาน</option><option value="closed">ปิดรับงาน</option></select></label><label className="vx-checkline"><input name="randomize" type="checkbox" defaultChecked/><span>สุ่มโจทย์ CAD/ข้อปรนัย และสลับตัวเลือกปรนัย</span></label></div><button className="vx-btn primary" disabled={saving||draftTotal<1||(sections.length>0&&selectedSections.length===0)}>{saving?'กำลังตรวจคลังโจทย์...':`บันทึก Assignment · ${draftTotal} ข้อ`}</button>
  </form></section>}
  {loading?<div className="vx-empty">กำลังโหลด...</div>:<section className="vx-assignment-grid">{items.length?items.map(a=>{const oldCount=a.vx_questions?.[0]?.count||0,hasHistory=startedAssignments.has(Number(a.id)),type=a.assignment_type||'cad',targetIds=assignmentSections[Number(a.id)]||[];return <article className="vx-assignment-card" key={a.id}><div className="vx-assignment-main"><div className="vx-assignment-icon"><BookOpen size={20}/></div><div className="vx-assignment-copy"><div className="vx-assignment-title-row"><h3>{a.title}</h3><span className={`vx-assignment-status ${a.status}`}>{statusLabel[a.status]||a.status}</span></div><p>{a.course||'ไม่ระบุวิชา'}</p><div className="vx-assignment-meta"><span>ครู {teacherMap[a.created_by]||'—'}</span><span>{typeLabel[type]||type}</span><span>{diffLabel[a.difficulty]||a.difficulty}</span>{Number(a.cad_question_count||0)>0&&<><span>CAD {a.cad_question_count}</span><span>{Object.entries(assignmentCadCounts(a)).map(([k,v])=>`${cadCategoryLabel[k]||k} ${v}`).join(' · ')||'ทุก CAD Category'}</span>{a.cad_lot&&<span>Lot {a.cad_lot}</span>}</>}{Number(a.mcq_question_count||0)>0&&<><span>ปรนัย {a.mcq_question_count}</span>{a.mcq_category_code&&<span>MCQ {a.mcq_category_code}</span>}</>}<span>รวม {a.question_count} ข้อ</span>{targetIds.length?targetIds.map(id=><span key={id}>Section {sectionMap[id]?.name||id}</span>):<span>Legacy · ทั้งโรงเรียน</span>}{hasHistory&&<span><LockKeyhole size={12}/>ล็อกกติกาแล้ว</span>}</div></div></div><div className="vx-assignment-footer"><div className="vx-assignment-note"><UsersRound size={14}/>{hasHistory?'มีนักเรียนเริ่มงานแล้ว':'ยังไม่มีประวัตินักเรียน'}</div><div className="vx-assignment-actions">{a.status!=='open'&&<button className="vx-link secondary" disabled={busyId===a.id} onClick={()=>setStatus(a,'open')}>เปิดรับงาน</button>}{a.status==='open'&&<button className="vx-link secondary" disabled={busyId===a.id} onClick={()=>setStatus(a,'closed')}>ปิดรับงาน</button>}<Link className="vx-link primary" href={`/verifyx/teacher/assignment/${a.id}`}>จัดการ<ChevronRight size={15}/></Link>{!hasHistory&&oldCount===0&&<button className="vx-icon-btn danger" title="ลบ" disabled={busyId===a.id} onClick={()=>removeEmpty(a)}><Trash2 size={15}/></button>}</div></div></article>}):<div className="vx-empty">ยังไม่มี Assignment</div>}</section>}
 </div></main>
}
