'use client';

import {useEffect,useMemo,useState} from 'react';
import {Plus,Boxes,FileText,Image as ImageIcon,Power,Download,RefreshCw,SlidersHorizontal,Save} from 'lucide-react';
import {vx,VX_BUCKET} from '../../vxClient';
import TeacherNav from '../TeacherNav';

const diffLabel={basic:'Basic',pro:'Pro',advanced:'Advanced'};
const thaiKey={A:'ก',B:'ข',C:'ค',D:'ง'};
const categoryLabel={part_modeling:'Part Modeling',assembly:'Assembly',drawing:'Drawing',sheet_metal:'Sheet Metal',surface:'Surface',other:'Other'};
const categoryOptions=[['part_modeling','Part Modeling'],['assembly','Assembly'],['drawing','Drawing'],['sheet_metal','Sheet Metal'],['surface','Surface'],['other','Other']];

export default function QuestionBankPage(){
 const [families,setFamilies]=useState([]),[items,setItems]=useState([]),[schoolMcq,setSchoolMcq]=useState([]),[systemMcq,setSystemMcq]=useState([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const [mode,setMode]=useState('cad'),[mcqTab,setMcqTab]=useState('school'),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 const [cadCategory,setCadCategory]=useState('all'),[cadLot,setCadLot]=useState('all');
 const [showFamily,setShowFamily]=useState(false),[showVariant,setShowVariant]=useState(false),[showMcq,setShowMcq]=useState(false),[showOrganize,setShowOrganize]=useState(false),[selectedSystem,setSelectedSystem]=useState([]);

 async function load(){
  setLoading(true);setError('');
  const [{data:f,error:fe},{data:q,error:qe},{data:m,error:me},{data:s,error:se}]=await Promise.all([
   vx.from('vx_question_families').select('*').order('difficulty').order('category').order('lot').order('code'),
   vx.from('vx_question_bank').select('*').order('id'),
   vx.rpc('vx_teacher_school_mcq_list'),
   vx.rpc('vx_teacher_system_mcq_list')
  ]);
  const err=fe||qe||me||se;if(err)setError(err.message);
  setFamilies(f||[]);setItems(q||[]);setSchoolMcq(m||[]);setSystemMcq(s||[]);setLoading(false)
 }
 useEffect(()=>{load()},[]);

 const familyMap=useMemo(()=>Object.fromEntries(families.map(f=>[f.id,f])),[families]);
 const cadCategories=useMemo(()=>Array.from(new Set(families.map(f=>f.category).filter(Boolean))).sort(),[families]);
 const cadLots=useMemo(()=>Array.from(new Set(families.filter(f=>cadCategory==='all'||f.category===cadCategory).map(f=>f.lot||'General').filter(Boolean))).sort(),[families,cadCategory]);
 const shownCad=useMemo(()=>{const q=search.toLowerCase().trim();return items.filter(x=>{const f=familyMap[x.family_id];return (filter==='all'||f?.difficulty===filter)&&(cadCategory==='all'||f?.category===cadCategory)&&(cadLot==='all'||(f?.lot||'General')===cadLot)&&(!q||`${x.title} ${f?.name||''} ${f?.code||''} ${f?.category||''} ${f?.lot||''}`.toLowerCase().includes(q))})},[items,familyMap,filter,search,cadCategory,cadLot]);
 const shownSchool=useMemo(()=>{const q=search.toLowerCase().trim();return schoolMcq.filter(x=>(filter==='all'||x.difficulty===filter)&&(!q||`${x.stem} ${x.subject} ${x.category_name} ${x.category_code}`.toLowerCase().includes(q)))},[schoolMcq,filter,search]);
 const shownSystem=useMemo(()=>{const q=search.toLowerCase().trim();return systemMcq.filter(x=>(filter==='all'||x.difficulty===filter)&&(!q||`${x.stem} ${x.subject} ${x.category_name} ${x.category_code}`.toLowerCase().includes(q)))},[systemMcq,filter,search]);

 async function addFamily(e){
  e.preventDefault();if(saving)return;setSaving(true);setError('');
  const form=e.currentTarget,fd=new FormData(form);
  const {error}=await vx.from('vx_question_families').insert({
   code:String(fd.get('code')).trim().toUpperCase(),
   name:String(fd.get('name')).trim(),
   category:String(fd.get('category')||'part_modeling'),
   lot:String(fd.get('lot')||'General').trim()||'General',
   difficulty:String(fd.get('difficulty')),
   description:String(fd.get('description')||'').trim()
  });
  setSaving(false);if(error)return setError(error.message);form.reset();setShowFamily(false);setMessage('เพิ่ม Family แล้ว');load()
 }
 async function updateFamily(e,familyId){
  e.preventDefault();if(saving)return;setSaving(true);setError('');
  const fd=new FormData(e.currentTarget);
  const {error}=await vx.from('vx_question_families').update({
   category:String(fd.get('category')||'part_modeling'),
   lot:String(fd.get('lot')||'General').trim()||'General',
   updated_at:new Date().toISOString()
  }).eq('id',familyId);
  setSaving(false);if(error)return setError(error.message);setMessage('อัปเดต Category / Lot แล้ว');load()
 }
 async function upload(file,folder){if(!file?.name)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`question-bank/${folder}/${crypto.randomUUID()}-${safe}`;const {error}=await vx.storage.from(VX_BUCKET).upload(path,file,{upsert:false});if(error)throw error;return path}
 async function addVariant(e){e.preventDefault();if(saving)return;setSaving(true);setError('');const form=e.currentTarget;try{const fd=new FormData(form),drawing=fd.get('drawing'),image=fd.get('modelImage');const drawingPath=await upload(drawing,'drawing'),imagePath=image?.name?await upload(image,'model'):null;const {error}=await vx.from('vx_question_bank').insert({family_id:Number(fd.get('familyId')),variant_code:String(fd.get('variantCode')).trim().toUpperCase(),title:String(fd.get('title')).trim(),drawing_path:drawingPath,drawing_name:drawing?.name||null,model_image_path:imagePath,model_image_name:image?.name||null,show_model_preview:Boolean(imagePath)&&fd.get('preview')==='on',reference_volume:Number(fd.get('volume')).toFixed(3),reference_area:Number(fd.get('area')).toFixed(3),reference_mass:Number(fd.get('mass')).toFixed(3),reference_com_x:Number(fd.get('x')).toFixed(3),reference_com_y:Number(fd.get('y')).toFixed(3),reference_com_z:Number(fd.get('z')).toFixed(3)});if(error)throw error;form.reset();setShowVariant(false);setMessage('เพิ่ม CAD Variant แล้ว');await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function addMcq(e){e.preventDefault();if(saving)return;setSaving(true);setError('');setMessage('');const form=e.currentTarget,fd=new FormData(form);try{const choices=['A','B','C','D'].map(k=>String(fd.get(`choice${k}`)||'').trim());const {error}=await vx.rpc('vx_teacher_create_mcq_question',{p_subject:String(fd.get('subject')||'SolidWorks').trim()||'SolidWorks',p_category_code:String(fd.get('categoryCode')||'').trim(),p_category_name:String(fd.get('categoryName')||'').trim(),p_difficulty:String(fd.get('difficulty')||'basic'),p_stem:String(fd.get('stem')||'').trim(),p_choices:choices,p_correct_key:String(fd.get('correct')||'A'),p_explanation:String(fd.get('explanation')||'').trim(),p_status:String(fd.get('status')||'active')});if(error)throw error;form.reset();setShowMcq(false);setMessage('เพิ่มข้อสอบปรนัยใน School Bank แล้ว');await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function toggleCad(q){const value=!q.is_active;const {error}=await vx.from('vx_question_bank').update({is_active:value,updated_at:new Date().toISOString()}).eq('id',q.id);if(error)return setError(error.message);setMessage(value?'เปิดใช้ CAD Variant แล้ว':'ปิดใช้ CAD Variant แล้ว');load()}
 async function toggleMcq(q){const next=q.status==='active'?'archived':'active';const {error}=await vx.rpc('vx_teacher_set_mcq_status',{p_question_id:q.id,p_status:next});if(error)return setError(error.message);setMessage(next==='active'?'เปิดใช้ข้อสอบแล้ว':'ปิดใช้ข้อสอบแล้ว');load()}
 async function importSelected(){if(!selectedSystem.length||saving)return;setSaving(true);setError('');const {data,error}=await vx.rpc('vx_teacher_import_system_mcq_selected',{p_question_ids:selectedSystem});setSaving(false);if(error)return setError(error.message);setSelectedSystem([]);setMessage(`นำเข้า ${Number(data||0)} ข้อจาก System Bank แล้ว`);load()}
 function toggleSystem(id){setSelectedSystem(xs=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id])}
 async function openFile(path){if(!path)return;const {data,error}=await vx.storage.from(VX_BUCKET).createSignedUrl(path,300);if(error)return setError(error.message);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 function changeCategory(value){setCadCategory(value);setCadLot('all')}

 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="bank"/>
  <header className="vx-top"><div><p className="vx-kicker">QUESTION BANK</p><h1>คลังโจทย์</h1><p>School Central Question Bank · CAD Family/Variant + ปรนัย พร้อม Category และ Lot</p></div><div className="vx-toolbar"><button className="vx-btn secondary" onClick={load}><RefreshCw size={15}/>Refresh</button>{mode==='cad'?<><button className="vx-btn secondary" onClick={()=>setShowOrganize(v=>!v)}><SlidersHorizontal size={15}/>จัดหมวด Family</button><button className="vx-btn secondary" onClick={()=>setShowFamily(v=>!v)}><Boxes size={15}/>เพิ่ม Family</button><button className="vx-btn primary" onClick={()=>setShowVariant(v=>!v)}><Plus size={15}/>เพิ่ม Variant</button></>:mcqTab==='school'?<button className="vx-btn primary" onClick={()=>setShowMcq(v=>!v)}><Plus size={15}/>เพิ่มข้อปรนัย</button>:<button className="vx-btn primary" disabled={!selectedSystem.length||saving} onClick={importSelected}><Download size={15}/>นำเข้า {selectedSystem.length} ข้อ</button>}</div></header>
  {message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}

  <div className="vx-toolbar" style={{marginTop:14}}><button className={`vx-btn ${mode==='cad'?'primary':'secondary'}`} onClick={()=>setMode('cad')}>CAD / Mass Properties</button><button className={`vx-btn ${mode==='mcq'?'primary':'secondary'}`} onClick={()=>{setMode('mcq');setShowFamily(false);setShowVariant(false);setShowOrganize(false)}}>ปรนัย / Multiple Choice</button></div>
  {mode==='mcq'&&<div className="vx-toolbar" style={{marginTop:8}}><button className={`vx-btn ${mcqTab==='school'?'primary':'secondary'}`} onClick={()=>setMcqTab('school')}>School Bank · {schoolMcq.length}</button><button className={`vx-btn ${mcqTab==='system'?'primary':'secondary'}`} onClick={()=>setMcqTab('system')}>System Bank · {systemMcq.length}</button></div>}

  <section className="vx-card" style={{marginTop:10,padding:12}}>
   <div className="vx-form-row"><label>ค้นหา<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="คำถาม / Family / Category / Lot"/></label><label>Difficulty<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทั้งหมด</option><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label></div>
   {mode==='cad'&&<div className="vx-form-row" style={{marginTop:10}}><label>Category<select value={cadCategory} onChange={e=>changeCategory(e.target.value)}><option value="all">ทุก Category</option>{cadCategories.map(c=><option key={c} value={c}>{categoryLabel[c]||c}</option>)}</select></label><label>Lot<select value={cadLot} onChange={e=>setCadLot(e.target.value)}><option value="all">ทุก Lot</option>{cadLots.map(l=><option key={l} value={l}>{l}</option>)}</select></label></div>}
  </section>

  {mode==='cad'&&showOrganize&&<section className="vx-card"><p className="vx-kicker">ORGANIZE</p><h3>จัด Category / Lot ของ Family</h3><p>Variant ทุกตัวใน Family เดียวกันจะใช้ Category และ Lot เดียวกัน</p><div className="vx-list">{families.map(f=><form key={f.id} className="vx-item" onSubmit={e=>updateFamily(e,f.id)} style={{alignItems:'end'}}><div style={{flex:'1 1 220px'}}><b>{f.code} · {f.name}</b><p>{diffLabel[f.difficulty]} · {categoryLabel[f.category]||f.category} · Lot {f.lot||'General'}</p></div><label style={{minWidth:180}}>Category<select name="category" defaultValue={f.category||'part_modeling'}>{categoryOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{minWidth:150}}>Lot<input name="lot" defaultValue={f.lot||'General'} placeholder="เช่น LOT-01"/></label><button className="vx-file" disabled={saving}><Save size={14}/>บันทึก</button></form>)}</div></section>}

  {mode==='cad'&&showFamily&&<section className="vx-card"><h3>เพิ่ม Question Family</h3><form className="vx-form" onSubmit={addFamily}><div className="vx-form-row"><label>Family Code<input name="code" placeholder="P-006" required/></label><label>ระดับ<select name="difficulty" defaultValue="basic"><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label></div><div className="vx-form-row"><label>Category<select name="category" defaultValue="part_modeling">{categoryOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Lot<input name="lot" defaultValue="General" placeholder="เช่น LOT-01" required/></label></div><label>ชื่อ Family<input name="name" required/></label><label>คำอธิบาย<textarea name="description" rows="2"/></label><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึก Family'}</button></form></section>}

  {mode==='cad'&&showVariant&&<section className="vx-card"><h3>เพิ่ม CAD Variant</h3><form className="vx-form" onSubmit={addVariant}><div className="vx-form-row"><label>Family<select name="familyId" required defaultValue=""><option value="" disabled>เลือก Family</option>{families.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name} · {categoryLabel[f.category]||f.category} · {f.lot||'General'} · {diffLabel[f.difficulty]}</option>)}</select></label><label>Variant Code<input name="variantCode" placeholder="A" required/></label></div><label>ชื่อโจทย์<input name="title" required/></label><label>Drawing PDF<input name="drawing" type="file" accept="application/pdf,.pdf" required/></label><div className="vx-mass-grid"><label>Volume mm³<input name="volume" type="number" step="0.001" required/></label><label>Surface Area mm²<input name="area" type="number" step="0.001" required/></label><label>Mass g<input name="mass" type="number" step="0.001" required/></label><label>COM X<input name="x" type="number" step="0.001" required/></label><label>COM Y<input name="y" type="number" step="0.001" required/></label><label>COM Z<input name="z" type="number" step="0.001" required/></label></div><label>Model Reference Image<input name="modelImage" type="file" accept="image/png,image/jpeg,image/webp"/></label><label><span><input name="preview" type="checkbox"/> แสดง Model Image ให้นักเรียนเห็น</span></label><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึก Variant'}</button></form></section>}

  {mode==='mcq'&&mcqTab==='school'&&showMcq&&<section className="vx-card"><p className="vx-kicker">NEW MCQ</p><h3>เพิ่มข้อสอบปรนัย</h3><form className="vx-form" onSubmit={addMcq}><div className="vx-form-row"><label>Subject<input name="subject" defaultValue="SolidWorks" required/></label><label>Difficulty<select name="difficulty" defaultValue="basic"><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label></div><div className="vx-form-row"><label>Category Code<input name="categoryCode" placeholder="เช่น SKETCH"/></label><label>Category Name<input name="categoryName" placeholder="เช่น Sketch Tools"/></label></div><label>คำถาม<textarea name="stem" rows="3" required/></label>{['A','B','C','D'].map(k=><label key={k}>ตัวเลือก {thaiKey[k]} ({k})<input name={`choice${k}`} required/></label>)}<div className="vx-form-row"><label>เฉลย<select name="correct" defaultValue="A"><option value="A">ก (A)</option><option value="B">ข (B)</option><option value="C">ค (C)</option><option value="D">ง (D)</option></select></label><label>สถานะ<select name="status" defaultValue="active"><option value="active">พร้อมใช้</option><option value="draft">Draft</option></select></label></div><label>คำอธิบายเฉลย<textarea name="explanation" rows="2"/></label><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึกข้อสอบ'}</button></form></section>}

  {loading?<div className="vx-empty">กำลังโหลดคลังโจทย์...</div>:mode==='cad'?<section className="vx-list">{shownCad.length?shownCad.map(q=>{const f=familyMap[q.family_id];return <article className="vx-card" key={q.id}><div className="vx-top"><div><p className="vx-kicker">{f?.code||'FAMILY'} · Variant {q.variant_code} · {diffLabel[f?.difficulty]||''}</p><h3>{q.title}</h3><p>{f?.name} · {categoryLabel[f?.category]||f?.category||'Part Modeling'} · Lot {f?.lot||'General'}</p></div><span className={`vx-progress ${q.is_active?'final':'muted'}`}>{q.is_active?'พร้อมใช้':'ปิดใช้'}</span></div><div className="vx-toolbar"><button className="vx-file" disabled={!q.drawing_path} onClick={()=>openFile(q.drawing_path)}><FileText size={14}/>Drawing</button>{q.model_image_path&&<button className="vx-file" onClick={()=>openFile(q.model_image_path)}><ImageIcon size={14}/>Model</button>}<button className="vx-file" onClick={()=>toggleCad(q)}><Power size={14}/>{q.is_active?'ปิดใช้':'เปิดใช้'}</button></div><div className="vx-tags"><span>{categoryLabel[f?.category]||f?.category}</span><span>Lot {f?.lot||'General'}</span><span>Volume {Number(q.reference_volume).toFixed(3)}</span><span>Area {Number(q.reference_area).toFixed(3)}</span><span>Mass {Number(q.reference_mass).toFixed(3)}</span><span>COM {Number(q.reference_com_x).toFixed(3)}, {Number(q.reference_com_y).toFixed(3)}, {Number(q.reference_com_z).toFixed(3)}</span><span>Tol V {Number(q.volume_tolerance_percent||0).toFixed(2)}%</span><span>Tol A {Number(q.area_tolerance_percent||0).toFixed(2)}%</span></div></article>}):<div className="vx-empty">ไม่พบโจทย์ CAD ตาม Category / Lot / Difficulty ที่เลือก</div>}</section>
  :mcqTab==='school'?<section className="vx-list">{shownSchool.length?shownSchool.map(q=><article className="vx-card" key={q.id}><div className="vx-top"><div><p className="vx-kicker">MCQ · {diffLabel[q.difficulty]}{q.category_name?` · ${q.category_name}`:''}</p><h3>{q.stem}</h3><p>{q.subject}{q.category_code?` · ${q.category_code}`:''} · {q.source||'School Bank'}</p></div><span className={`vx-progress ${q.status==='active'?'final':'muted'}`}>{q.status==='active'?'พร้อมใช้':q.status}</span></div><div className="vx-list" style={{marginTop:10}}>{(q.choices||[]).map(c=><div key={c.key} className="vx-item" style={{padding:'9px 12px'}}><span><b>{thaiKey[c.key]||c.key}.</b> {c.text}</span>{c.is_correct&&<span className="vx-progress final">✓ เฉลย</span>}</div>)}</div>{q.explanation&&<p style={{marginTop:10}}>คำอธิบาย: {q.explanation}</p>}<div className="vx-toolbar" style={{marginTop:10}}><button className="vx-file" onClick={()=>toggleMcq(q)}><Power size={14}/>{q.status==='active'?'ปิดใช้':'เปิดใช้'}</button></div></article>):<div className="vx-empty">ไม่พบข้อสอบปรนัยใน School Bank</div>}</section>
  :<section className="vx-list">{shownSystem.length?shownSystem.map(q=><label className="vx-card" key={q.id} style={{display:'block',cursor:q.imported?'default':'pointer'}}><div className="vx-top"><div><p className="vx-kicker">SYSTEM MCQ · {diffLabel[q.difficulty]}{q.category_name?` · ${q.category_name}`:''}</p><h3>{q.stem}</h3><p>{q.subject}{q.category_code?` · ${q.category_code}`:''}</p></div>{q.imported?<span className="vx-progress final">มีใน School Bank แล้ว</span>:<input type="checkbox" checked={selectedSystem.includes(q.id)} onChange={()=>toggleSystem(q.id)}/>}</div><div className="vx-list" style={{marginTop:10}}>{(q.choices||[]).map(c=><div key={c.key} className="vx-item" style={{padding:'8px 11px'}}><span><b>{thaiKey[c.key]||c.key}.</b> {c.text}</span>{c.is_correct&&<span>✓</span>}</div>)}</div></label>):<div className="vx-empty">ไม่พบข้อใน System Bank ตามตัวกรอง</div>}</section>}
 </div></main>;
}
