'use client';

import {useEffect,useMemo,useState} from 'react';
import {Plus,Boxes,FileText,Image as ImageIcon,Power} from 'lucide-react';
import {vx,VX_BUCKET} from '../../vxClient';
import TeacherNav from '../TeacherNav';

const diffLabel={basic:'Basic',pro:'Pro',advanced:'Advanced'};
export default function QuestionBankPage(){
 const [families,setFamilies]=useState([]),[items,setItems]=useState([]),[mcq,setMcq]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[showFamily,setShowFamily]=useState(false),[showVariant,setShowVariant]=useState(false),[saving,setSaving]=useState(false),[filter,setFilter]=useState('all'),[mode,setMode]=useState('cad');
 async function load(){setLoading(true);setError('');const [{data:f,error:fe},{data:q,error:qe},{data:m,error:me}]=await Promise.all([vx.from('vx_question_families').select('*').order('difficulty').order('code'),vx.from('vx_question_bank').select('*').order('id'),vx.from('vx_central_questions').select('id,subject,category_code,category_name,difficulty,stem,status,source').eq('scope','school').eq('question_type','mcq').order('id')]);if(fe||qe||me)setError((fe||qe||me).message);setFamilies(f||[]);setItems(q||[]);setMcq(m||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const familyMap=useMemo(()=>Object.fromEntries(families.map(f=>[f.id,f])),[families]);
 const shown=useMemo(()=>items.filter(q=>filter==='all'||familyMap[q.family_id]?.difficulty===filter),[items,familyMap,filter]);
 const shownMcq=useMemo(()=>mcq.filter(q=>filter==='all'||q.difficulty===filter),[mcq,filter]);
 async function addFamily(e){e.preventDefault();if(saving)return;setSaving(true);const form=e.currentTarget,fd=new FormData(form);const {error}=await vx.from('vx_question_families').insert({code:String(fd.get('code')).trim().toUpperCase(),name:String(fd.get('name')).trim(),category:'part_modeling',difficulty:String(fd.get('difficulty')),description:String(fd.get('description')||'').trim()});setSaving(false);if(error)return setError(error.message);form.reset();setShowFamily(false);setMessage('เพิ่ม Family ในคลังโจทย์แล้ว');load()}
 async function upload(file,folder){if(!file?.name)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`question-bank/${folder}/${crypto.randomUUID()}-${safe}`;const {error}=await vx.storage.from(VX_BUCKET).upload(path,file,{upsert:false});if(error)throw error;return path}
 async function addVariant(e){e.preventDefault();if(saving)return;setSaving(true);setError('');const form=e.currentTarget;try{const fd=new FormData(form),drawing=fd.get('drawing'),image=fd.get('modelImage');const drawingPath=await upload(drawing,'drawing'),imagePath=image?.name?await upload(image,'model'):null;const {error}=await vx.from('vx_question_bank').insert({family_id:Number(fd.get('familyId')),variant_code:String(fd.get('variantCode')).trim().toUpperCase(),title:String(fd.get('title')).trim(),drawing_path:drawingPath,drawing_name:drawing?.name||null,model_image_path:imagePath,model_image_name:image?.name||null,show_model_preview:Boolean(imagePath)&&fd.get('preview')==='on',reference_volume:Number(fd.get('volume')).toFixed(3),reference_area:Number(fd.get('area')).toFixed(3),reference_mass:Number(fd.get('mass')).toFixed(3),reference_com_x:Number(fd.get('x')).toFixed(3),reference_com_y:Number(fd.get('y')).toFixed(3),reference_com_z:Number(fd.get('z')).toFixed(3)});if(error)throw error;form.reset();setShowVariant(false);setMessage('เพิ่ม Variant ในคลังโจทย์แล้ว');await load()}catch(err){setError(err.message)}finally{setSaving(false)}}
 async function toggle(q){const value=!q.is_active;setItems(xs=>xs.map(x=>x.id===q.id?{...x,is_active:value}:x));const {error}=await vx.from('vx_question_bank').update({is_active:value,updated_at:new Date().toISOString()}).eq('id',q.id);if(error){setError(error.message);load()}}
 async function openFile(path){if(!path)return;const {data,error}=await vx.storage.from(VX_BUCKET).createSignedUrl(path,300);if(error)return setError(error.message);window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="bank"/><header className="vx-top"><div><p className="vx-kicker">QUESTION BANK</p><h1>คลังโจทย์</h1><p>School Central Question Bank · CAD / Mass Properties และข้อสอบปรนัย</p></div><div className="vx-toolbar">{mode==='cad'&&<><button className="vx-btn secondary" onClick={()=>setShowFamily(v=>!v)}><Boxes size={15}/>เพิ่ม Family</button><button className="vx-btn primary" onClick={()=>setShowVariant(v=>!v)}><Plus size={15}/>เพิ่ม Variant</button></>}</div></header>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
 <div className="vx-toolbar" style={{marginTop:14}}><button className={`vx-btn ${mode==='cad'?'primary':'secondary'}`} onClick={()=>setMode('cad')}>CAD / Mass Properties</button><button className={`vx-btn ${mode==='mcq'?'primary':'secondary'}`} onClick={()=>{setMode('mcq');setShowFamily(false);setShowVariant(false)}}>ปรนัย / Multiple Choice</button></div><div className="vx-toolbar" style={{marginTop:10}}>{['all','basic','pro','advanced'].map(x=><button key={x} className={`vx-btn ${filter===x?'primary':'secondary'}`} onClick={()=>setFilter(x)}>{x==='all'?'ทั้งหมด':diffLabel[x]}</button>)}</div>
 {mode==='cad'&&showFamily&&<section className="vx-card"><h3>เพิ่ม Question Family</h3><form className="vx-form" onSubmit={addFamily}><div className="vx-form-row"><label>Family Code<input name="code" required/></label><label>ระดับ<select name="difficulty" defaultValue="basic"><option value="basic">Basic</option><option value="pro">Pro</option><option value="advanced">Advanced</option></select></label></div><label>ชื่อ Family<input name="name" required/></label><label>คำอธิบาย<textarea name="description" rows="2"/></label><button className="vx-btn primary" disabled={saving}>บันทึก Family</button></form></section>}
 {mode==='cad'&&showVariant&&<section className="vx-card"><h3>เพิ่ม CAD Variant</h3><form className="vx-form" onSubmit={addVariant}><div className="vx-form-row"><label>Family<select name="familyId" required defaultValue=""><option value="" disabled>เลือก Family</option>{families.map(f=><option key={f.id} value={f.id}>{f.code} · {f.name} · {diffLabel[f.difficulty]}</option>)}</select></label><label>Variant Code<input name="variantCode" required/></label></div><label>ชื่อโจทย์<input name="title" required/></label><label>Drawing PDF<input name="drawing" type="file" accept="application/pdf,.pdf" required/></label><div className="vx-mass-grid"><label>Volume mm³<input name="volume" type="number" step="0.001" required/></label><label>Surface Area mm²<input name="area" type="number" step="0.001" required/></label><label>Mass g<input name="mass" type="number" step="0.001" required/></label><label>COM X<input name="x" type="number" step="0.001" required/></label><label>COM Y<input name="y" type="number" step="0.001" required/></label><label>COM Z<input name="z" type="number" step="0.001" required/></label></div><label>Model Reference Image<input name="modelImage" type="file" accept="image/png,image/jpeg,image/webp"/></label><label><span><input name="preview" type="checkbox"/> แสดง Model Image ให้นักเรียนเห็น</span></label><button className="vx-btn primary" disabled={saving}>บันทึก Variant</button></form></section>}
 {loading?<div className="vx-empty">กำลังโหลดคลังโจทย์...</div>:mode==='cad'?<section className="vx-list">{shown.length?shown.map(q=>{const f=familyMap[q.family_id];return <article className="vx-card" key={q.id}><div className="vx-top" style={{marginBottom:10}}><div><p className="vx-kicker">{f?.code||'FAMILY'} · {q.variant_code} · {diffLabel[f?.difficulty]||''}</p><h3>{q.title}</h3><p>{f?.name} · Part Modeling</p></div><span className="vx-status">{q.is_active?'พร้อมใช้':'ปิดใช้'}</span></div><div className="vx-toolbar"><button className="vx-file" disabled={!q.drawing_path} onClick={()=>openFile(q.drawing_path)}><FileText size={14}/>Drawing</button>{q.model_image_path&&<button className="vx-file" onClick={()=>openFile(q.model_image_path)}><ImageIcon size={14}/>Model</button>}<button className="vx-file" onClick={()=>toggle(q)}><Power size={14}/>{q.is_active?'ปิดใช้':'เปิดใช้'}</button></div><div className="vx-tags"><span>V {Number(q.reference_volume).toFixed(3)}</span><span>A {Number(q.reference_area).toFixed(3)}</span><span>M {Number(q.reference_mass).toFixed(3)}</span><span>COM {Number(q.reference_com_x).toFixed(3)}, {Number(q.reference_com_y).toFixed(3)}, {Number(q.reference_com_z).toFixed(3)}</span></div></article>}):<div className="vx-empty">ไม่พบโจทย์ CAD ในระดับนี้</div>}</section>:<section className="vx-list">{shownMcq.length?shownMcq.map(q=><article className="vx-card" key={q.id}><div className="vx-top"><div><p className="vx-kicker">MCQ · {diffLabel[q.difficulty]}{q.category_name?` · ${q.category_name}`:''}</p><h3>{q.stem}</h3><p>{q.subject}{q.category_code?` · ${q.category_code}`:''}</p></div><span className="vx-status">{q.status==='active'?'พร้อมใช้':q.status}</span></div><div className="vx-tags"><span>{q.source||'School Bank'}</span></div></article>):<div className="vx-empty">ยังไม่มีข้อสอบปรนัยในระดับนี้</div>}</section>}
 </div></main>;
}
