'use client';

import {useEffect,useMemo,useState} from 'react';
import {Plus,School,UsersRound} from 'lucide-react';
import TeacherNav from '../TeacherNav';
import {vx} from '../../vxClient';

export default function SchoolProfile(){
 const [school,setSchool]=useState(null),[team,setTeam]=useState([]),[invites,setInvites]=useState([]),[structure,setStructure]=useState([]),[userId,setUserId]=useState(null),[editing,setEditing]=useState(false),[name,setName]=useState(''),[code,setCode]=useState(''),[inviteName,setInviteName]=useState(''),[inviteEmail,setInviteEmail]=useState(''),[saving,setSaving]=useState(false),[inviting,setInviting]=useState(false),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[showDepartment,setShowDepartment]=useState(false),[sectionDepartment,setSectionDepartment]=useState(null);
 const me=useMemo(()=>team.find(x=>x.user_id===userId)||null,[team,userId]);
 const isOwner=me?.role==='owner';
 const departments=useMemo(()=>{
  const map=new Map();
  for(const r of structure){
   if(!map.has(r.department_id))map.set(r.department_id,{id:r.department_id,code:r.department_code,name:r.department_name,is_active:r.department_active,sections:[]});
   if(r.section_id)map.get(r.department_id).sections.push({id:r.section_id,code:r.section_code,name:r.section_name,academic_year:r.academic_year,term:r.term,is_active:r.section_active});
  }
  return [...map.values()];
 },[structure]);
 async function load(){
  setLoading(true);setError('');
  const [{data:i,error:ie},{data:t,error:te},{data:iv,error:ive},{data:u,error:ue},{data:st,error:ste}]=await Promise.all([
   vx.rpc('vx_teacher_institution'),vx.rpc('vx_teacher_team'),vx.rpc('vx_teacher_invites_list'),vx.auth.getUser(),vx.rpc('vx_teacher_academic_structure')
  ]);
  const err=ie||te||ive||ue||ste;if(err)setError(err.message);
  const s=i?.[0]||null;setSchool(s);setName(s?.name||'');setCode(s?.code||'');setTeam(t||[]);setInvites(iv||[]);setStructure(st||[]);setUserId(u?.user?.id||null);setLoading(false)
 }
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();if(!isOwner||saving)return;setSaving(true);setError('');setMessage('');const {data,error}=await vx.rpc('vx_update_teacher_institution',{p_name:name,p_code:code});setSaving(false);if(error){setError(error.message);return}const s=data?.[0]||null;setSchool(s);setName(s?.name||'');setCode(s?.code||'');setEditing(false);setMessage('บันทึกข้อมูลโรงเรียนแล้ว')}
 async function addDepartment(e){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy('department');setError('');const {error}=await vx.rpc('vx_create_department',{p_code:String(fd.get('code')).trim().toUpperCase(),p_name:String(fd.get('name')).trim()});setBusy('');if(error)return setError(error.message);setShowDepartment(false);setMessage('เพิ่ม Department แล้ว');await load()}
 async function addSection(e,departmentId){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(`section-${departmentId}`);setError('');const {error}=await vx.rpc('vx_create_section',{p_department_id:departmentId,p_code:String(fd.get('code')).trim().toUpperCase(),p_name:String(fd.get('name')).trim(),p_academic_year:String(fd.get('year')||'').trim(),p_term:String(fd.get('term')||'').trim()});setBusy('');if(error)return setError(error.message);setSectionDepartment(null);setMessage('เพิ่ม Section แล้ว');await load()}
 async function invite(e){e.preventDefault();if(!isOwner||inviting)return;setInviting(true);setError('');const {error}=await vx.rpc('vx_invite_teacher',{p_email:inviteEmail,p_display_name:inviteName});setInviting(false);if(error){setError(error.message);return}setInviteEmail('');setInviteName('');setMessage('บันทึกคำเชิญแล้ว ให้ครูสมัครด้วย Email นี้จากเมนู “ได้รับคำเชิญ”');await load()}
 async function revoke(i){if(!confirm(`ยกเลิกคำเชิญ ${i.email} ?`))return;setBusy(`i-${i.id}`);const {error}=await vx.rpc('vx_revoke_teacher_invite',{p_invite_id:i.id});setBusy('');if(error)return setError(error.message);setMessage('ยกเลิกคำเชิญแล้ว');await load()}
 async function remove(t){if(!confirm(`นำ ${t.display_name} ออกจากทีมครู?`))return;setBusy(`r-${t.user_id}`);const {error}=await vx.rpc('vx_remove_teacher',{p_user_id:t.user_id});setBusy('');if(error)return setError(error.message);setMessage('นำครูออกจากทีมแล้ว');await load()}
 async function transfer(t){if(!confirm(`โอน Owner ให้ ${t.display_name} ?`))return;if(!confirm('ยืนยันอีกครั้ง: หลังโอนคุณจะกลายเป็น Teacher'))return;setBusy(`o-${t.user_id}`);const {error}=await vx.rpc('vx_transfer_owner',{p_new_owner_user_id:t.user_id});setBusy('');if(error)return setError(error.message);setMessage('โอน Owner เรียบร้อยแล้ว');await load()}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="school"/>
  <div className="vx-top"><div><p className="vx-kicker">TEACHER MODE</p><h1>School Profile</h1><p>ข้อมูลโรงเรียน โครงสร้างการเรียน และ Teacher Team</p></div></div>
  {message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
  {loading?<div className="vx-empty">กำลังโหลด...</div>:<>
   <section className="vx-card" style={{marginBottom:16}}><div className="vx-top"><div><p className="vx-kicker">SCHOOL</p><h2>{school?.name||'—'}</h2><p>School Code: <b>{school?.code||'—'}</b></p></div><span className={`vx-progress ${isOwner?'working':'muted'}`}>{isOwner?'Owner':'Teacher'}</span></div>{isOwner&&!editing&&<button className="vx-btn secondary" onClick={()=>setEditing(true)}>แก้ไขข้อมูลโรงเรียน</button>}{editing&&<form className="vx-form" onSubmit={save} style={{marginTop:14}}><label>ชื่อโรงเรียน / สถาบัน<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>School Code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={20} required/></label><div className="vx-toolbar"><button type="button" className="vx-btn secondary" onClick={()=>{setEditing(false);setName(school?.name||'');setCode(school?.code||'')}}>ยกเลิก</button><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึกการเปลี่ยนแปลง'}</button></div></form>}{!isOwner&&<div className="vx-empty" style={{marginTop:12}}>Teacher ดูข้อมูลโรงเรียนได้ แต่แก้ไขไม่ได้</div>}</section>

   <section className="vx-card" style={{marginBottom:16}}><div className="vx-top"><div><p className="vx-kicker">ACADEMIC STRUCTURE</p><h2>Department & Section</h2><p>Question Bank ยังเป็นคลังกลางทั้งโรงเรียน · Section ใช้แบ่งกลุ่มนักเรียนและงานที่มอบหมาย</p></div>{isOwner&&<button className="vx-btn secondary" onClick={()=>setShowDepartment(v=>!v)}><Plus size={15}/>Department</button>}</div>
    {showDepartment&&<form className="vx-form" onSubmit={addDepartment} style={{marginBottom:16}}><div className="vx-form-row"><label>Department Code<input name="code" placeholder="เช่น ME" required/></label><label>ชื่อ Department<input name="name" placeholder="เช่น Mechanical Engineering" required/></label></div><div className="vx-toolbar"><button type="button" className="vx-btn secondary" onClick={()=>setShowDepartment(false)}>ยกเลิก</button><button className="vx-btn primary" disabled={busy==='department'}>{busy==='department'?'กำลังเพิ่ม...':'เพิ่ม Department'}</button></div></form>}
    {departments.length?<div className="vx-list">{departments.map(d=><article className="vx-item" key={d.id} style={{alignItems:'stretch'}}><div style={{width:'100%'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><div className="vx-tags" style={{marginTop:0}}><span>{d.code}</span></div><h3 style={{marginTop:6}}>{d.name}</h3></div>{isOwner&&<button className="vx-link secondary" onClick={()=>setSectionDepartment(sectionDepartment===d.id?null:d.id)}><Plus size={14}/>Section</button>}</div>
      {d.sections.length?<div className="vx-list" style={{marginTop:12}}>{d.sections.map(s=><div className="vx-item" key={s.id}><div><div style={{display:'flex',alignItems:'center',gap:8}}><UsersRound size={15}/><h3>{s.name}</h3></div><p>{s.code}{s.academic_year?` · ปี ${s.academic_year}`:''}{s.term?` · เทอม ${s.term}`:''}</p></div><span className={`vx-progress ${s.is_active?'final':'muted'}`}>{s.is_active?'Active':'Inactive'}</span></div>)}</div>:<div className="vx-empty">ยังไม่มี Section</div>}
      {sectionDepartment===d.id&&<form className="vx-form" onSubmit={e=>addSection(e,d.id)} style={{marginTop:12}}><div className="vx-form-row"><label>Section Code<input name="code" placeholder="เช่น ME-01" required/></label><label>ชื่อ Section<input name="name" placeholder="เช่น Section 01" required/></label></div><div className="vx-form-row"><label>ปีการศึกษา<input name="year" placeholder="เช่น 2569"/></label><label>เทอม<input name="term" placeholder="เช่น 1"/></label></div><div className="vx-toolbar"><button type="button" className="vx-btn secondary" onClick={()=>setSectionDepartment(null)}>ยกเลิก</button><button className="vx-btn primary" disabled={busy===`section-${d.id}`}>{busy===`section-${d.id}`?'กำลังเพิ่ม...':'เพิ่ม Section'}</button></div></form>}
     </div></article>)}</div>:<div className="vx-empty"><School size={18}/>ยังไม่มี Department · เริ่มจากสร้าง Department แล้วค่อยเพิ่ม Section</div>}
   </section>

   <section className="vx-card"><p className="vx-kicker">TEACHER TEAM</p><h2>ครูในโรงเรียน</h2><div className="vx-list">{team.map(t=><div className="vx-item" key={t.user_id}><div><h3>{t.display_name}</h3><p>{t.user_id===userId?'บัญชีของคุณ':''}</p></div><div className="vx-toolbar"><span className={`vx-progress ${t.role==='owner'?'working':'muted'}`}>{t.role==='owner'?'Owner':'Teacher'}</span>{isOwner&&t.role==='teacher'&&t.user_id!==userId&&<><button className="vx-link secondary" disabled={busy!==''} onClick={()=>transfer(t)}>{busy===`o-${t.user_id}`?'กำลังโอน...':'โอน Owner'}</button><button className="vx-link secondary" disabled={busy!==''} onClick={()=>remove(t)}>{busy===`r-${t.user_id}`?'กำลังนำออก...':'นำออก'}</button></>}</div></div>)}</div>{isOwner&&<form className="vx-form" onSubmit={invite} style={{marginTop:18}}><h3>เชิญครูเพิ่ม</h3><label>ชื่อครู (ถ้าทราบ)<input value={inviteName} onChange={e=>setInviteName(e.target.value)}/></label><label>Email<input value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} type="email" required/></label><button className="vx-btn primary" disabled={inviting}>{inviting?'กำลังบันทึก...':'เชิญครูด้วย Email'}</button></form>}{isOwner&&invites.length>0&&<div style={{marginTop:18}}><h3>คำเชิญ</h3><div className="vx-list">{invites.map(i=><div className="vx-item" key={i.id}><div><b>{i.email}</b><p>{i.display_name||'—'} · {i.status}</p></div>{i.status==='pending'&&<button className="vx-link secondary" disabled={busy!==''} onClick={()=>revoke(i)}>{busy===`i-${i.id}`?'กำลังยกเลิก...':'ยกเลิก Invite'}</button>}</div>)}</div></div>}</section>
  </>}
 </div></main>;
}
