'use client';

import {useEffect,useMemo,useState} from 'react';
import TeacherNav from '../TeacherNav';
import {vx} from '../../vxClient';
export default function SchoolProfile(){
 const [school,setSchool]=useState(null),[team,setTeam]=useState([]),[userId,setUserId]=useState(null),[editing,setEditing]=useState(false),[name,setName]=useState(''),[code,setCode]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const me=useMemo(()=>team.find(x=>x.user_id===userId)||null,[team,userId]);const isOwner=me?.role==='owner';
 async function load(){setLoading(true);const [{data:i,error:ie},{data:t,error:te},{data:u,error:ue}]=await Promise.all([vx.rpc('vx_teacher_institution'),vx.rpc('vx_teacher_team'),vx.auth.getUser()]);const err=ie||te||ue;if(err)setError(err.message);const s=i?.[0]||null;setSchool(s);setName(s?.name||'');setCode(s?.code||'');setTeam(t||[]);setUserId(u?.user?.id||null);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();if(!isOwner||saving)return;setSaving(true);setError('');setMessage('');const {data,error}=await vx.rpc('vx_update_teacher_institution',{p_name:name,p_code:code});setSaving(false);if(error){setError(error.message);return}const s=data?.[0]||null;setSchool(s);setName(s?.name||'');setCode(s?.code||'');setEditing(false);setMessage('บันทึกข้อมูลโรงเรียนแล้ว')}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="school"/><div className="vx-top"><div><p className="vx-kicker">TEACHER MODE</p><h1>School Profile</h1><p>ข้อมูลโรงเรียนและทีมครู</p></div></div>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}{loading?<div className="vx-empty">กำลังโหลด...</div>:<><section className="vx-card" style={{marginBottom:16}}><div className="vx-top"><div><p className="vx-kicker">SCHOOL</p><h2>{school?.name||'—'}</h2><p>School Code: <b>{school?.code||'—'}</b></p></div><span className={`vx-progress ${isOwner?'working':'muted'}`}>{isOwner?'Owner':'Teacher'}</span></div>{isOwner&&!editing&&<button className="vx-btn secondary" onClick={()=>setEditing(true)}>แก้ไขข้อมูลโรงเรียน</button>}{editing&&<form className="vx-form" onSubmit={save} style={{marginTop:14}}><label>ชื่อโรงเรียน / สถาบัน<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>School Code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={20} required/></label><div className="vx-toolbar"><button type="button" className="vx-btn secondary" onClick={()=>{setEditing(false);setName(school?.name||'');setCode(school?.code||'')}}>ยกเลิก</button><button className="vx-btn primary" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึกการเปลี่ยนแปลง'}</button></div></form>}{!isOwner&&<div className="vx-empty" style={{marginTop:12}}>Teacher ดูข้อมูลโรงเรียนได้ แต่แก้ไขไม่ได้</div>}</section><section className="vx-card"><p className="vx-kicker">TEACHER TEAM</p><h2>ครูในโรงเรียน</h2><div className="vx-list">{team.map(t=><div className="vx-item" key={t.user_id}><div><h3>{t.display_name}</h3><p>{t.user_id===userId?'บัญชีของคุณ':''}</p></div><span className={`vx-progress ${t.role==='owner'?'working':'muted'}`}>{t.role==='owner'?'Owner':'Teacher'}</span></div>)}</div><div className="vx-empty" style={{marginTop:14}}>การเชิญ/นำครูออก/โอน Owner จะย้ายมารวมใน School Profile ต่อจากนี้</div></section></>}</div></main>;
}
