'use client';

import {useEffect,useMemo,useState} from 'react';
import {vx} from '../../vxClient';
import TeacherNav from '../TeacherNav';

function QuestionSetting({q,onReload}){
 const [v,setV]=useState(Number(q.volume_tolerance_percent||1)); const [a,setA]=useState(Number(q.area_tolerance_percent||1));
 async function save(){const {error}=await vx.from('vx_questions').update({volume_tolerance_percent:Number(v).toFixed(3),area_tolerance_percent:Number(a).toFixed(3),updated_at:new Date().toISOString()}).eq('id',q.id);if(error)return alert(error.message);onReload()}
 return <div style={{display:'grid',gridTemplateColumns:'1fr 110px 110px auto',gap:8,alignItems:'end',padding:10,border:'1px solid #efddd2',borderRadius:12}}><div><b>ข้อ {q.question_number} · {q.title||'Question'}</b><div style={{fontSize:11,color:'#927667'}}>V {Number(q.reference_volume).toFixed(3)} · A {Number(q.reference_area).toFixed(3)}</div></div><label style={{fontSize:11}}>Vol Tol %<input value={v} type="number" step="0.001" min="0" onChange={e=>setV(e.target.value)} style={{width:'100%',padding:8,borderRadius:9,border:'1px solid #ead6ca'}}/></label><label style={{fontSize:11}}>Area Tol %<input value={a} type="number" step="0.001" min="0" onChange={e=>setA(e.target.value)} style={{width:'100%',padding:8,borderRadius:9,border:'1px solid #ead6ca'}}/></label><button className="vx-link secondary" onClick={save}>Save</button></div>
}
function AssignmentSetting({item,onReload}){
 const [status,setStatus]=useState(item.status); async function save(){const {error}=await vx.from('vx_assignments').update({status,max_attempts:1,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)return alert(error.message);onReload()}
 return <article className="vx-card" style={{marginBottom:12}}><h2 style={{marginTop:0}}>{item.title}</h2><p style={{color:'#927667'}}>{item.course||'ไม่ระบุวิชา'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'end',marginBottom:12}}><label>สถานะ<select value={status} onChange={e=>setStatus(e.target.value)} style={{display:'block',padding:9,borderRadius:10,border:'1px solid #ead6ca'}}><option value="draft">ฉบับร่าง</option><option value="open">เปิดรับงาน</option><option value="closed">ปิดรับงาน</option></select></label><div className="vx-status">Final Submit ครั้งเดียว</div><button className="vx-link primary" onClick={save}>บันทึก Assignment</button></div><div style={{display:'grid',gap:8}}>{(item.vx_questions||[]).sort((x,y)=>x.question_number-y.question_number).map(q=><QuestionSetting key={q.id} q={q} onReload={onReload}/>)}</div></article>
}

export default function SettingsPage(){
 const [items,setItems]=useState([]),[institution,setInstitution]=useState(null),[schoolName,setSchoolName]=useState(''),[schoolCode,setSchoolCode]=useState(''),[team,setTeam]=useState([]),[invites,setInvites]=useState([]),[meId,setMeId]=useState(null),[inviteEmail,setInviteEmail]=useState(''),[inviteName,setInviteName]=useState(''),[savingSchool,setSavingSchool]=useState(false),[inviting,setInviting]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const me=useMemo(()=>team.find(x=>x.user_id===meId)||null,[team,meId]);const isOwner=me?.role==='owner';
 async function load(){setLoading(true);setError('');const [{data,error},{data:inst,error:ie},{data:tm,error:te},{data:iv,error:ive},{data:user}]=await Promise.all([vx.from('vx_assignments').select('*, vx_questions(*)').order('created_at',{ascending:false}),vx.rpc('vx_teacher_institution'),vx.rpc('vx_teacher_team'),vx.rpc('vx_teacher_invites_list'),vx.auth.getUser()]);const err=error||ie||te||ive;if(err)setError(err.message);setItems(data||[]);const school=inst?.[0]||null;setInstitution(school);setSchoolName(school?.name||'');setSchoolCode(school?.code||'');setTeam(tm||[]);setInvites(iv||[]);setMeId(user?.user?.id||null);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function saveSchool(e){e.preventDefault();if(savingSchool)return;setSavingSchool(true);setError('');setMessage('');const {data,error}=await vx.rpc('vx_update_teacher_institution',{p_name:schoolName,p_code:schoolCode});setSavingSchool(false);if(error){setError(error.message);return}const school=data?.[0]||null;setInstitution(school);setSchoolName(school?.name||'');setSchoolCode(school?.code||'');setMessage('บันทึกข้อมูลโรงเรียนแล้ว')}
 async function inviteTeacher(e){e.preventDefault();if(inviting)return;setInviting(true);setError('');setMessage('');const {error}=await vx.rpc('vx_invite_teacher',{p_email:inviteEmail,p_display_name:inviteName});setInviting(false);if(error){setError(error.message);return}setInviteEmail('');setInviteName('');setMessage('บันทึกคำเชิญแล้ว · ให้ครูใช้ Email นี้ที่เมนู “ได้รับคำเชิญ”');await load()}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="settings"/><div className="vx-top"><div><p className="vx-kicker">TEACHER MODE</p><h1>Settings</h1><p>ตั้งค่าโรงเรียน ทีมครู Assignment และ Tolerance</p></div></div>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}
 {institution&&<section className="vx-card" style={{marginBottom:16}}><p className="vx-kicker">SCHOOL PROFILE</p><h2>ข้อมูลโรงเรียน</h2><p>School Code ใช้แยกนักเรียนคนละโรงเรียน แม้รหัสนักเรียนจะซ้ำกันก็ไม่ชนกัน</p><form className="vx-form" onSubmit={saveSchool}><label>ชื่อโรงเรียน / สถาบัน<input value={schoolName} onChange={e=>setSchoolName(e.target.value)} required/></label><label>School Code<input value={schoolCode} onChange={e=>setSchoolCode(e.target.value.toUpperCase())} required maxLength={20} placeholder="เช่น RMUTT-ME"/></label><div className="vx-result"><small>School Code ที่นักเรียนต้องกรอก</small><div className="vx-score" style={{fontSize:24}}>{schoolCode||'—'}</div></div><button className="vx-btn primary" disabled={savingSchool}>{savingSchool?'กำลังบันทึก...':'บันทึกข้อมูลโรงเรียน'}</button></form></section>}
 <section className="vx-card" style={{marginBottom:16}}><p className="vx-kicker">TEACHER TEAM</p><h2>ครูในโรงเรียน</h2><p>ทุกคนในทีมเห็น Assignments, Question Bank, Students และ Results ของโรงเรียนเดียวกัน</p><div className="vx-list">{team.map(t=><div className="vx-item" key={t.user_id}><div><h3>{t.display_name}</h3><p>{t.user_id===meId?'บัญชีของคุณ':''}</p></div><span className={`vx-progress ${t.role==='owner'?'working':'muted'}`}>{t.role==='owner'?'Owner':'Teacher'}</span></div>)}</div>
 {isOwner&&<form className="vx-form" onSubmit={inviteTeacher} style={{marginTop:18}}><h3>เชิญครูเพิ่ม</h3><label>ชื่อครู (ถ้าทราบ)<input value={inviteName} onChange={e=>setInviteName(e.target.value)} placeholder="เช่น อาจารย์สมชาย"/></label><label>Email<input value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} type="email" required placeholder="teacher@school.ac.th"/></label><button className="vx-btn primary" disabled={inviting}>{inviting?'กำลังบันทึกคำเชิญ...':'เชิญครูด้วย Email'}</button></form>}
 {isOwner&&invites.length>0&&<div style={{marginTop:18}}><h3>คำเชิญ</h3><div className="vx-list">{invites.map(i=><div className="vx-item" key={i.id}><div><b>{i.email}</b><p>{i.display_name||'—'} · {i.status==='pending'?'รอสมัคร/ยืนยันอีเมล':i.status==='accepted'?'เข้าร่วมแล้ว':'ยกเลิก'}</p></div><span className={`vx-progress ${i.status==='accepted'?'final':i.status==='pending'?'working':'muted'}`}>{i.status}</span></div>)}</div></div>}</section>
 {loading?<p>กำลังโหลด...</p>:items.map(i=><AssignmentSetting key={i.id} item={i} onReload={load}/>)}</div></main>;
}
