'use client';

import {useEffect,useState} from 'react';
import {vx} from '../../vxClient';
import TeacherNav from '../TeacherNav';

function QuestionSetting({q,onReload}){
 const [v,setV]=useState(Number(q.volume_tolerance_percent||1)); const [a,setA]=useState(Number(q.area_tolerance_percent||1));
 async function save(){const {error}=await vx.from('vx_questions').update({volume_tolerance_percent:Number(v).toFixed(3),area_tolerance_percent:Number(a).toFixed(3),updated_at:new Date().toISOString()}).eq('id',q.id);if(error)return alert(error.message);onReload()}
 return <div style={{display:'grid',gridTemplateColumns:'1fr 110px 110px auto',gap:8,alignItems:'end',padding:10,border:'1px solid #efddd2',borderRadius:12}}><div><b>ข้อ {q.question_number} · {q.title||'Question'}</b><div style={{fontSize:11,color:'#927667'}}>V {Number(q.reference_volume).toFixed(3)} · A {Number(q.reference_area).toFixed(3)}</div></div><label style={{fontSize:11}}>Vol Tol %<input value={v} type="number" step="0.001" min="0" onChange={e=>setV(e.target.value)} style={{width:'100%',padding:8,borderRadius:9,border:'1px solid #ead6ca'}}/></label><label style={{fontSize:11}}>Area Tol %<input value={a} type="number" step="0.001" min="0" onChange={e=>setA(e.target.value)} style={{width:'100%',padding:8,borderRadius:9,border:'1px solid #ead6ca'}}/></label><button className="vx-link secondary" onClick={save}>Save</button></div>
}
function AssignmentSetting({item,onReload}){
 const [status,setStatus]=useState(item.status); async function save(){const {error}=await vx.from('vx_assignments').update({status,max_attempts:1,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)return alert(error.message);onReload()}
 return <article className="vx-card" style={{marginBottom:12}}><h2 style={{marginTop:0}}>{item.title}</h2><p style={{color:'#927667'}}>{item.course||'ไม่ระบุวิชา'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'end',marginBottom:12}}><label>สถานะ<select value={status} onChange={e=>setStatus(e.target.value)} style={{display:'block',padding:9,borderRadius:10,border:'1px solid #ead6ca'}}><option value="draft">ฉบับร่าง</option><option value="open">เปิดรับงาน</option><option value="closed">ปิดรับงาน</option></select></label><div className="vx-status">Final Submit ครั้งเดียว</div><button className="vx-link primary" onClick={save}>บันทึก Assignment</button></div><div style={{display:'grid',gap:8}}>{(item.vx_questions||[]).sort((x,y)=>x.question_number-y.question_number).map(q=><QuestionSetting key={q.id} q={q} onReload={onReload}/>)}</div></article>
}
export default function SettingsPage(){
 const [items,setItems]=useState([]),[institution,setInstitution]=useState(null),[schoolName,setSchoolName]=useState(''),[schoolCode,setSchoolCode]=useState(''),[savingSchool,setSavingSchool]=useState(false),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');const [{data,error},{data:inst,error:ie}]=await Promise.all([vx.from('vx_assignments').select('*, vx_questions(*)').order('created_at',{ascending:false}),vx.rpc('vx_teacher_institution')]);if(error||ie)setError((error||ie).message);setItems(data||[]);const school=inst?.[0]||null;setInstitution(school);setSchoolName(school?.name||'');setSchoolCode(school?.code||'');setLoading(false)}
 useEffect(()=>{load()},[]);
 async function saveSchool(e){e.preventDefault();if(savingSchool)return;setSavingSchool(true);setError('');setMessage('');const {data,error}=await vx.rpc('vx_update_teacher_institution',{p_name:schoolName,p_code:schoolCode});setSavingSchool(false);if(error){setError(error.message);return}const school=data?.[0]||null;setInstitution(school);setSchoolName(school?.name||'');setSchoolCode(school?.code||'');setMessage('บันทึกข้อมูลโรงเรียนแล้ว · ให้นักเรียนใช้ School Code นี้เมื่อเข้า Student Mode')}
 return <main className="vx-page"><div className="vx-wrap"><TeacherNav active="settings"/><div className="vx-top"><div><p className="vx-kicker">TEACHER MODE</p><h1>Settings</h1><p>ตั้งค่าโรงเรียน Assignment และ Tolerance</p></div></div>{message&&<div className="vx-success">{message}</div>}{error&&<div className="vx-error">{error}</div>}{institution&&<section className="vx-card" style={{marginBottom:16}}><p className="vx-kicker">SCHOOL PROFILE</p><h2>ข้อมูลโรงเรียน</h2><p>School Code ใช้แยกนักเรียนคนละโรงเรียน แม้รหัสนักเรียนจะซ้ำกันก็ไม่ชนกัน</p><form className="vx-form" onSubmit={saveSchool}><label>ชื่อโรงเรียน / สถาบัน<input value={schoolName} onChange={e=>setSchoolName(e.target.value)} required/></label><label>School Code<input value={schoolCode} onChange={e=>setSchoolCode(e.target.value.toUpperCase())} required maxLength={20} placeholder="เช่น RMUTT-ME"/><small style={{fontWeight:500,color:'#927667'}}>ใช้ A-Z, 0-9, _ หรือ - เท่านั้น · 3-20 ตัว</small></label><div className="vx-result"><small>School Code ที่นักเรียนต้องกรอก</small><div className="vx-score" style={{fontSize:24}}>{schoolCode||'—'}</div></div><button className="vx-btn primary" disabled={savingSchool}>{savingSchool?'กำลังบันทึก...':'บันทึกข้อมูลโรงเรียน'}</button></form><p style={{marginBottom:0}}>Teacher, Students, Assignments, Question Bank และ Results จะถูกแยกตามโรงเรียนนี้โดยอัตโนมัติ</p></section>}{loading?<p>กำลังโหลด...</p>:items.map(i=><AssignmentSetting key={i.id} item={i} onReload={load}/>)}</div></main>;
}
